//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.20 at 03:37:02 PM IST 
//


package com.ubiquity.common.jaxb.user;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userPrivacySettingsJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userPrivacySettingsJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}Long" minOccurs="0"/>
 *         &lt;element name="privateUser" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *         &lt;element name="social" type="{}userSocialSettingsJAXB" minOccurs="0"/>
 *         &lt;element name="email" type="{}userEmailSettingsJAXB" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userPrivacySettingsJAXB", propOrder = {
    "userId",
    "privateUser",
    "social",
    "email"
})
public class UserPrivacySettingsJAXB
    implements Serializable
{

    private final static Long serialVersionUID = 12344L;
    protected Long userId;
    protected Boolean privateUser;
    protected UserSocialSettingsJAXB social;
    protected UserEmailSettingsJAXB email;

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUserId(Long value) {
        this.userId = value;
    }

    public Boolean isSetUserId() {
        return (this.userId!= null);
    }

    /**
     * Gets the value of the privateUser property.
     * 
     */
    public Boolean isPrivateUser() {
        return privateUser;
    }

    /**
     * Sets the value of the privateUser property.
     * 
     */
    public void setPrivateUser(Boolean value) {
        this.privateUser = value;
    }

    public Boolean isSetPrivateUser() {
        return true;
    }

    /**
     * Gets the value of the social property.
     * 
     * @return
     *     possible object is
     *     {@link UserSocialSettingsJAXB }
     *     
     */
    public UserSocialSettingsJAXB getSocial() {
        return social;
    }

    /**
     * Sets the value of the social property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserSocialSettingsJAXB }
     *     
     */
    public void setSocial(UserSocialSettingsJAXB value) {
        this.social = value;
    }

    public Boolean isSetSocial() {
        return (this.social!= null);
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link UserEmailSettingsJAXB }
     *     
     */
    public UserEmailSettingsJAXB getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserEmailSettingsJAXB }
     *     
     */
    public void setEmail(UserEmailSettingsJAXB value) {
        this.email = value;
    }

    public Boolean isSetEmail() {
        return (this.email!= null);
    }

}
