//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.20 at 03:37:02 PM IST 
//


package com.ubiquity.common.jaxb.user;

import java.io.Serializable;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for userEmailSettingsJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userEmailSettingsJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}Long" minOccurs="0"/>
 *         &lt;element name="likeNotification" type="{http://www.w3.org/2001/XMLSchema}Boolean" minOccurs="0"/>
 *         &lt;element name="shareNotification" type="{http://www.w3.org/2001/XMLSchema}Boolean" minOccurs="0"/>
 *         &lt;element name="commentNotification" type="{http://www.w3.org/2001/XMLSchema}Boolean" minOccurs="0"/>
 *         &lt;element name="followNotification" type="{http://www.w3.org/2001/XMLSchema}Boolean" minOccurs="0"/>
 *         &lt;element name="weeklyNotification" type="{http://www.w3.org/2001/XMLSchema}Boolean" minOccurs="0"/>
 *         &lt;element name="secondLevelNotification" type="{http://www.w3.org/2001/XMLSchema}Boolean" minOccurs="0"/>
 *         &lt;element name="updateDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userEmailSettingsJAXB", propOrder = {
    "userId",
    "likeNotification",
    "shareNotification",
    "commentNotification",
    "followNotification",
    "weeklyNotification",
    "secondLevelNotification",
    "updateDate"
})
public class UserEmailSettingsJAXB
    implements Serializable
{

    private final static Long serialVersionUID = 12344L;
    protected Long userId;
    protected Boolean likeNotification;
    protected Boolean shareNotification;
    protected Boolean commentNotification;
    protected Boolean followNotification;
    protected Boolean weeklyNotification;
    protected Boolean secondLevelNotification;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Date updateDate;

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUserId(Long value) {
        this.userId = value;
    }

    public Boolean isSetUserId() {
        return (this.userId!= null);
    }

    /**
     * Gets the value of the likeNotification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getLikeNotification() {
        return likeNotification;
    }

    /**
     * Sets the value of the likeNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLikeNotification(Boolean value) {
        this.likeNotification = value;
    }

    public Boolean isSetLikeNotification() {
        return (this.likeNotification!= null);
    }

    /**
     * Gets the value of the shareNotification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getShareNotification() {
        return shareNotification;
    }

    /**
     * Sets the value of the shareNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShareNotification(Boolean value) {
        this.shareNotification = value;
    }

    public Boolean isSetShareNotification() {
        return (this.shareNotification!= null);
    }

    /**
     * Gets the value of the commentNotification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getCommentNotification() {
        return commentNotification;
    }

    /**
     * Sets the value of the commentNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCommentNotification(Boolean value) {
        this.commentNotification = value;
    }

    public Boolean isSetCommentNotification() {
        return (this.commentNotification!= null);
    }

    /**
     * Gets the value of the followNotification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getFollowNotification() {
        return followNotification;
    }

    /**
     * Sets the value of the followNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFollowNotification(Boolean value) {
        this.followNotification = value;
    }

    public Boolean isSetFollowNotification() {
        return (this.followNotification!= null);
    }

    /**
     * Gets the value of the weeklyNotification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getWeeklyNotification() {
        return weeklyNotification;
    }

    /**
     * Sets the value of the weeklyNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWeeklyNotification(Boolean value) {
        this.weeklyNotification = value;
    }

    public Boolean isSetWeeklyNotification() {
        return (this.weeklyNotification!= null);
    }

    /**
     * Gets the value of the secondLevelNotification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSecondLevelNotification() {
        return secondLevelNotification;
    }

    /**
     * Sets the value of the secondLevelNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSecondLevelNotification(Boolean value) {
        this.secondLevelNotification = value;
    }

    public Boolean isSetSecondLevelNotification() {
        return (this.secondLevelNotification!= null);
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateDate(Date value) {
        this.updateDate = value;
    }

    public Boolean isSetUpdateDate() {
        return (this.updateDate!= null);
    }

}
