//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.11 at 01:55:25 PM IST 
//

package com.ubiquity.common.jaxb.stream;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.ubiquity.common.jaxb.cards.AppCardsJAXB;
import com.ubiquity.common.jaxb.cards.FlippingCardJAXB;
import com.ubiquity.common.jaxb.ecomm.Countable;
import com.ubiquity.common.jaxb.ecomm.ECommOrderTransactionJAXB;
import com.ubiquity.common.jaxb.ecomm.EcommerceProductFullJAXB;
import com.ubiquity.common.jaxb.ecomm.EcommerceProductJAXB;
import com.ubiquity.common.jaxb.ecomm.EcommerceStoreJAXB;
import com.ubiquity.common.jaxb.reaction.ReactionJAXB;
import com.ubiquity.common.jaxb.stream.campaign.CampaignJAXB;
import com.ubiquity.common.jaxb.stream.campaign.CampaignLimitedJAXB;
import com.ubiquity.common.jaxb.stream.content.ContentJAXB;
import com.ubiquity.common.jaxb.themecollection.ThemeCollectionDetailsJAXB;
import com.ubiquity.common.jaxb.votecard.VotecardJAXB;

/**
 * <p>
 * Java class for GenericStreamEntry complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GenericStreamEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="entrytype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="userDetails" type="{}UserStreamEntryRepresentationJAXB"/>
 *         &lt;element name="producerBranchDetails" type="{}ProducerBranchStreamEntryRepresentationJAXB"/>
 *         &lt;element name="dealDetails" type="{}DealStreamEntryRepresentationJAXB"/>
 *         &lt;element name="productDetails" type="{}ProductStreamEntryRepresentationJAXB"/>
 *         &lt;element name="producerDetails" type="{}ProducerStreamEntryRepresentationJAXB"/>
 *         &lt;element name="producerProductDetails" type="{}ProducerProductEntryRepresentationJAXB"/>
 *         &lt;element name="sponsoredPointDetails" type="{}SponsoredPointsStreamEntryRepresentationJAXB"/>
 *         &lt;element name="sponsoredRewardDetails" type="{}SponsoredRewardStreamEntryRepresentationJAXB"/>
 *         &lt;element name="producerReviewDetails" type="{}ProducerReviewStreamEntryRepresentationJAXB"/>
 *         &lt;element name="sharedRecommendationDetails" type="{}SharedRecommendationStreamEntryRepresentationJAXB"/>
 *         &lt;element name="productReviewDetails" type="{}ProductReviewStreamEntryRepresentationJAXB"/>
 *         &lt;element name="dealReviewDetails" type="{}DealReviewStreamEntryRepresentationJAXB"/>
 *         &lt;element name="smsTrendDetails" type="{}SMSProductTrendStreamEntryJAXB"/>
 *         &lt;element name="productBuzzDetails" type="{}ProductBuzzDetailsStreamEntryJAXB"/>
 *         &lt;element name="producerBuzzDetails" type="{}ProducerBuzzDetailsStreamEntryJAXB"/>
 *         &lt;element name="userFollowProducerDetails" type="{}UserFollowProducerStreamEntryJAXB"/>
 *         &lt;element name="userWishProductDetails" type="{}UserWishProductStreamEntryJAXB"/>
 *         &lt;element name="userTriedProductDetails" type="{}UserTriedProductStreamEntryJAXB"/>
 *         &lt;element name="userWishProducerDetails" type="{}UserWishProducerStreamEntryJAXB"/>
 *         &lt;element name="userTriedProducerDetails" type="{}UserTriedProducerStreamEntryJAXB"/>
 *         &lt;element name="userGetDealDetails" type="{}UserGetDealStreamEntryJAXB"/>
 *         &lt;element name="userFollowProductDetails" type="{}UserFollowProductStreamEntryJAXB"/>
 *         &lt;element name="userFollowDealDetails" type="{}UserFollowDealStreamEntryJAXB"/>
 *         &lt;element name="userFollowDealReviewDetails" type="{}UserFollowDealReviewStreamEntryJAXB"/>
 *         &lt;element name="userFollowProducerReviewDetails" type="{}UserFollowProducerReviewStreamEntryJAXB"/>
 *         &lt;element name="userFollowProductReviewDetails" type="{}UserFollowProductReviewStreamEntryJAXB"/>
 *         &lt;element name="userCommentProducerReviewDetails" type="{}UserCommentProducerReviewStreamEntryJAXB"/>
 *         &lt;element name="userAddedProducerProductReviewToBoardDetails" type="{}UserAddedProducerProductReviewToBoardStreamEntryJAXB"/>
 *         &lt;element name="userCommentProducerProductReviewDetails" type="{}UserCommentProducerProductReviewStreamEntryJAXB"/>
 *         &lt;element name="userFollowTagDetails" type="{}UserFollowTagStreamEntryJAXB"/>
 *         &lt;element name="userFollowUserDetails" type="{}UserFollowUserStreamEntryJAXB"/>
 *         &lt;element name="userFollowUserReviewDetails" type="{}UserFollowUserStreamEntryJAXB"/>
 *         &lt;element name="userRewardStreamEntryJAXB" type="{}UserRewardStreamEntryJAXB"/>
 *         &lt;element name="userBadgeStreamEntryJAXB" type="{}UserBadgeStreamEntryJAXB"/>
 *         &lt;element name="ProducerLandingPageDetails" type="{}ProducerLandingPageStreamEntryRepresentationJAXB"/>
 *         &lt;element name="ProducerProductLandingPageDetails" type="{}ProducerProductLandingPageEntryRepresentationJAXB"/>
 *         &lt;element name="ProducerProductDetailsExtended" type="{}ProducerProductEntryExtendedRepresentationJAXB"/>
 *         &lt;element name="ProducerDetailsExtended" type="{}ProducerEntryExtendedRepresentationJAXB"/>
 *         &lt;element name="ProducerProductReviewDetailsExtended" type="{}ProducerProductReviewExtendedStreamEntryRepresentationJAXB"/>
 *         &lt;element name="FMRecommendation" type="{}FMRecommendationEntryRepresentationJAXB"/>
 *         &lt;element name="UserBoardDetailsExtended" type="{}UserBoardStreamEntryExtendedJAXB"/>
 *         &lt;element name="UserBoardDetails" type="{}UserBoardStreamEntryJAXB"/>
 *         &lt;element name="StreamInformation" type="{}StreamInformationRepresentationJAXB"/>
 *         &lt;element name="look" type="{}FashionLookJAXB"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericStreamEntry", propOrder = { "id", "entrytype", "weight", "timestamp", "userDetails", "producerBranchDetails", "dealDetails", "productDetails", "producerDetails",
		"producerProductDetails", "sponsoredPointDetails", "sponsoredRewardDetails", "producerReviewDetails", "sharedRecommendationDetails", "productReviewDetails", "dealReviewDetails",
		"smsTrendDetails", "productBuzzDetails", "producerBuzzDetails", "userFollowProducerDetails", "userWishProductDetails", "userTriedProductDetails", "userWishProducerDetails",
		"userTriedProducerDetails", "userGetDealDetails", "userFollowProductDetails", "userFollowDealDetails", "userFollowDealReviewDetails", "userFollowProducerReviewDetails",
		"userFollowProductReviewDetails", "userFollowLookDetails", "userCommentProducerReviewDetails", "userAddedProducerProductReviewToBoardDetails", "userCommentProducerProductReviewDetails",
		"userFollowTagDetails", "userFollowUserDetails", "userFollowUserReviewDetails", "userRewardStreamEntryJAXB", "userBadgeStreamEntryJAXB", "producerLandingPageDetails",
		"producerProductLandingPageDetails", "producerProductDetailsExtended", "producerDetailsExtended", "producerProductReviewDetailsExtended", "fmRecommendation", "userBoardDetailsExtended",
		"userBoardDetails", "streamInformation", "ecommerceProductFullJAXB", "look", "lookExtended", "lookCommonJAXB", "ecommerceStoreJAXB", "ecommerceProductJAXB", "themeCollectionJAXB",
		"themeCollectionDetailsJAXB", "collegeCampusJAXB", "searchFacetJAXB", "contentJAXB", "collateApisPaginationJAXB", "campaignJAXB", "campaignLimitedJAXB", "groupJAXB", "appCardsJAXB",
		"ecommOrderTransactionJAXB", "reactionJAXB", "votecardJAXB"

})
@XmlRootElement
public class GenericStreamEntry implements Serializable, Countable, Comparable<GenericStreamEntry> {

	private final static Long serialVersionUID = 12343L;
	protected Long id;
	@XmlElement(required = true)   
	protected String entrytype;
	protected Long weight;
	protected Long timestamp;
	protected Long updateTimestamp;
	@XmlElement(required = true)
	protected UserStreamEntryRepresentationJAXB userDetails;
	@XmlElement(required = true)
	protected ProducerBranchStreamEntryRepresentationJAXB producerBranchDetails;
	@XmlElement(required = true)
	protected DealStreamEntryRepresentationJAXB dealDetails;
	@XmlElement(required = true)
	protected ProductStreamEntryRepresentationJAXB productDetails;
	@XmlElement(required = true)
	protected ProducerStreamEntryRepresentationJAXB producerDetails;
	@XmlElement(required = true)
	protected ProducerProductEntryRepresentationJAXB producerProductDetails;
	@XmlElement(required = true)
	protected SponsoredPointsStreamEntryRepresentationJAXB sponsoredPointDetails;
	@XmlElement(required = true)
	protected SponsoredRewardStreamEntryRepresentationJAXB sponsoredRewardDetails;
	@XmlElement(required = true)
	protected ProducerReviewStreamEntryRepresentationJAXB producerReviewDetails;
	@XmlElement(required = true)
	protected SharedRecommendationStreamEntryRepresentationJAXB sharedRecommendationDetails;
	@XmlElement(required = true)
	protected ProductReviewStreamEntryRepresentationJAXB productReviewDetails;
	@XmlElement(required = true)
	protected DealReviewStreamEntryRepresentationJAXB dealReviewDetails;
	@XmlElement(required = true)
	protected SMSProductTrendStreamEntryJAXB smsTrendDetails;
	@XmlElement(required = true)
	protected ProductBuzzDetailsStreamEntryJAXB productBuzzDetails;
	@XmlElement(required = true)
	protected ProducerBuzzDetailsStreamEntryJAXB producerBuzzDetails;
	@XmlElement(required = true)
	protected UserFollowProducerStreamEntryJAXB userFollowProducerDetails;
	@XmlElement(required = true)
	protected UserWishProductStreamEntryJAXB userWishProductDetails;
	@XmlElement(required = true)
	protected UserTriedProductStreamEntryJAXB userTriedProductDetails;
	@XmlElement(required = true)
	protected UserWishProducerStreamEntryJAXB userWishProducerDetails;
	@XmlElement(required = true)
	protected UserTriedProducerStreamEntryJAXB userTriedProducerDetails;
	@XmlElement(required = true)
	protected UserGetDealStreamEntryJAXB userGetDealDetails;
	@XmlElement(required = true)
	protected UserFollowProductStreamEntryJAXB userFollowProductDetails;
	@XmlElement(required = true)
	protected UserFollowDealStreamEntryJAXB userFollowDealDetails;
	@XmlElement(required = true)
	protected UserFollowDealReviewStreamEntryJAXB userFollowDealReviewDetails;
	@XmlElement(required = true)
	protected UserFollowProducerReviewStreamEntryJAXB userFollowProducerReviewDetails;
	@XmlElement(required = true)
	protected UserFollowProductReviewStreamEntryJAXB userFollowProductReviewDetails;
	@XmlElement(required = true)
	protected UserFollowFashionLookStreamEntryJAXB userFollowLookDetails;
	@XmlElement(required = true)
	protected UserCommentProducerReviewStreamEntryJAXB userCommentProducerReviewDetails;
	@XmlElement(required = true)
	protected UserAddedProducerProductReviewToBoardStreamEntryJAXB userAddedProducerProductReviewToBoardDetails;
	@XmlElement(required = true)
	protected UserCommentProducerProductReviewStreamEntryJAXB userCommentProducerProductReviewDetails;
	@XmlElement(required = true)
	protected UserFollowTagStreamEntryJAXB userFollowTagDetails;
	@XmlElement(required = true)
	protected UserFollowUserStreamEntryJAXB userFollowUserDetails;
	@XmlElement(required = true)
	protected UserFollowUserStreamEntryJAXB userFollowUserReviewDetails;
	@XmlElement(required = true)
	protected UserRewardStreamEntryJAXB userRewardStreamEntryJAXB;
	@XmlElement(required = true)
	protected UserBadgeStreamEntryJAXB userBadgeStreamEntryJAXB;
	@XmlElement(name = "ProducerLandingPageDetails", required = true)
	protected ProducerLandingPageStreamEntryRepresentationJAXB producerLandingPageDetails;
	@XmlElement(name = "ProducerProductLandingPageDetails", required = true)
	protected ProducerProductLandingPageEntryRepresentationJAXB producerProductLandingPageDetails;
	@XmlElement(name = "ProducerProductDetailsExtended", required = true)
	protected ProducerProductEntryExtendedRepresentationJAXB producerProductDetailsExtended;
	@XmlElement(name = "ProducerDetailsExtended", required = true)
	protected ProducerEntryExtendedRepresentationJAXB producerDetailsExtended;
	@XmlElement(name = "ProducerProductReviewDetailsExtended", required = true)
	protected ProducerProductReviewExtendedStreamEntryRepresentationJAXB producerProductReviewDetailsExtended;
	@XmlElement(name = "FMRecommendation", required = true)
	protected FMRecommendationEntryRepresentationJAXB fmRecommendation;
	@XmlElement(name = "UserBoardDetailsExtended", required = true)
	protected UserBoardStreamEntryExtendedJAXB userBoardDetailsExtended;
	@XmlElement(name = "UserBoardDetails", required = true)
	protected UserBoardStreamEntryJAXB userBoardDetails;
	@XmlElement(name = "StreamInformation", required = true)
	protected StreamInformationRepresentationJAXB streamInformation;
	@XmlElement(required = true)
	protected FashionLookJAXB look;
	@XmlElement(required = true)
	protected FashionLookExtendedJAXB lookExtended;
	@XmlElement(required = true)
	protected FashionLookCommonJAXB lookCommonJAXB;
	@XmlElement(required = true)
	protected EcommerceStoreJAXB ecommerceStoreJAXB;
	@XmlElement(required = true)
	protected EcommerceProductJAXB ecommerceProductJAXB;
	@XmlElement(required = true)
	protected EcommerceProductFullJAXB ecommerceProductFullJAXB;
	// @XmlElement(required = true)
	// protected ThemeCollectionJAXB themeCollectionJAXB;
	@XmlElement(required = true)
	protected ThemeCollectionDetailsJAXB themeCollectionDetailsJAXB;
	@XmlElement(required = true)
	protected CollegeCampusJAXB collegeCampusJAXB;
	@XmlElement(name = "searchFacetJAXB", required = true)
	protected SearchFacetJAXB searchFacetJAXB;
	@XmlElement(required = true)
	protected ContentJAXB contentJAXB;
	@XmlElement(name = "collateApisPaginationJAXB", required = true)
	protected CollateApisPaginationJAXB collateApisPaginationJAXB;
	@XmlElement(name = "campaignJAXB", required = false)
	protected CampaignJAXB campaignJAXB;
	@XmlElement(name = "campaignLimitedJAXB", required = false)
	protected CampaignLimitedJAXB campaignLimitedJAXB;
	@XmlElement(required = true)
	protected GroupJAXB groupJAXB;
	@XmlElement(required = true)
	protected AppCardsJAXB appCardsJAXB;
	@XmlElement(required = true)
	protected FlippingCardJAXB flippingCardJAXB;
	@XmlElement(required = false)
	protected String lookContext;

	@XmlElement(required = true)
	protected ECommOrderTransactionJAXB ecommOrderTransactionJAXB;
	@XmlElement(required = true)
	protected ReactionJAXB reactionJAXB;

	@XmlElement(required = false)
	protected VotecardJAXB votecardJAXB;

	/*
	 * 
	 * @XmlElement(required = true) protected StreamUserDetailJAXB
	 * streamUserDetail; // // @XmlElement(required = true) // protected
	 * LookUserDetailJAXB lookUserDetail;
	 */

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(Long value) {
		this.id = value;
	}

	public Boolean isSetId() {
		return true;
	}

	/**
	 * Gets the value of the entrytype property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEntrytype() {
		return entrytype;
	}

	/**
	 * Sets the value of the entrytype property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEntrytype(String value) {
		this.entrytype = value;
	}

	public Boolean isSetEntrytype() {
		return (this.entrytype != null);
	}

	/**
	 * Gets the value of the weight property.
	 * 
	 */
	public Long getWeight() {
		return weight;
	}

	public FashionLookExtendedJAXB getLookExtended() {
		return lookExtended;
	}

	public void setLookExtended(FashionLookExtendedJAXB lookExtended) {
		this.lookExtended = lookExtended;
	}

	/**
	 * Sets the value of the weight property.
	 * 
	 */

	public void setWeight(Long value) {
		this.weight = value;
	}

	public Boolean isSetWeight() {
		return true;
	}

	/**
	 * Gets the value of the timestamp property.
	 * 
	 */
	public Long getTimestamp() {
		return timestamp;
	}

	/**
	 * Sets the value of the timestamp property.
	 * 
	 */
	public void setTimestamp(Long value) {
		this.timestamp = value;
	}

	public Boolean isSetTimestamp() {
		return true;
	}

	/**
	 * Gets the value of the userDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserStreamEntryRepresentationJAXB }
	 * 
	 */
	public UserStreamEntryRepresentationJAXB getUserDetails() {
		return userDetails;
	}

	/**
	 * Sets the value of the userDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setUserDetails(UserStreamEntryRepresentationJAXB value) {
		this.userDetails = value;
	}

	public Boolean isSetUserDetails() {
		return (this.userDetails != null);
	}

	/**
	 * Gets the value of the producerBranchDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProducerBranchStreamEntryRepresentationJAXB }
	 * 
	 */
	public ProducerBranchStreamEntryRepresentationJAXB getProducerBranchDetails() {
		return producerBranchDetails;
	}

	/**
	 * Sets the value of the producerBranchDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProducerBranchStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setProducerBranchDetails(ProducerBranchStreamEntryRepresentationJAXB value) {
		this.producerBranchDetails = value;
	}

	public Boolean isSetProducerBranchDetails() {
		return (this.producerBranchDetails != null);
	}

	/**
	 * Gets the value of the dealDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.DealStreamEntryRepresentationJAXB }
	 * 
	 */
	public DealStreamEntryRepresentationJAXB getDealDetails() {
		return dealDetails;
	}

	/**
	 * Sets the value of the dealDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.DealStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setDealDetails(DealStreamEntryRepresentationJAXB value) {
		this.dealDetails = value;
	}

	public Boolean isSetDealDetails() {
		return (this.dealDetails != null);
	}

	/**
	 * Gets the value of the productDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProductStreamEntryRepresentationJAXB }
	 * 
	 */
	public ProductStreamEntryRepresentationJAXB getProductDetails() {
		return productDetails;
	}

	/**
	 * Sets the value of the productDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProductStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setProductDetails(ProductStreamEntryRepresentationJAXB value) {
		this.productDetails = value;
	}

	public Boolean isSetProductDetails() {
		return (this.productDetails != null);
	}

	/**
	 * Gets the value of the producerDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProducerStreamEntryRepresentationJAXB }
	 * 
	 */
	public ProducerStreamEntryRepresentationJAXB getProducerDetails() {
		return producerDetails;
	}

	/**
	 * Sets the value of the producerDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProducerStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setProducerDetails(ProducerStreamEntryRepresentationJAXB value) {
		this.producerDetails = value;
	}

	public Boolean isSetProducerDetails() {
		return (this.producerDetails != null);
	}

	/**
	 * Gets the value of the producerProductDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProducerProductEntryRepresentationJAXB }
	 * 
	 */
	public ProducerProductEntryRepresentationJAXB getProducerProductDetails() {
		return producerProductDetails;
	}

	/**
	 * Sets the value of the producerProductDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProducerProductEntryRepresentationJAXB }
	 * 
	 */
	public void setProducerProductDetails(ProducerProductEntryRepresentationJAXB value) {
		this.producerProductDetails = value;
	}

	public Boolean isSetProducerProductDetails() {
		return (this.producerProductDetails != null);
	}

	/**
	 * Gets the value of the sponsoredPointDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.SponsoredPointsStreamEntryRepresentationJAXB }
	 * 
	 */
	public SponsoredPointsStreamEntryRepresentationJAXB getSponsoredPointDetails() {
		return sponsoredPointDetails;
	}

	/**
	 * Sets the value of the sponsoredPointDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.SponsoredPointsStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setSponsoredPointDetails(SponsoredPointsStreamEntryRepresentationJAXB value) {
		this.sponsoredPointDetails = value;
	}

	public Boolean isSetSponsoredPointDetails() {
		return (this.sponsoredPointDetails != null);
	}

	/**
	 * Gets the value of the sponsoredRewardDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.SponsoredRewardStreamEntryRepresentationJAXB }
	 * 
	 */
	public SponsoredRewardStreamEntryRepresentationJAXB getSponsoredRewardDetails() {
		return sponsoredRewardDetails;
	}

	/**
	 * Sets the value of the sponsoredRewardDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.SponsoredRewardStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setSponsoredRewardDetails(SponsoredRewardStreamEntryRepresentationJAXB value) {
		this.sponsoredRewardDetails = value;
	}

	public Boolean isSetSponsoredRewardDetails() {
		return (this.sponsoredRewardDetails != null);
	}

	/**
	 * Gets the value of the producerReviewDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProducerReviewStreamEntryRepresentationJAXB }
	 * 
	 */
	public ProducerReviewStreamEntryRepresentationJAXB getProducerReviewDetails() {
		return producerReviewDetails;
	}

	/**
	 * Sets the value of the producerReviewDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProducerReviewStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setProducerReviewDetails(ProducerReviewStreamEntryRepresentationJAXB value) {
		this.producerReviewDetails = value;
	}

	public Boolean isSetProducerReviewDetails() {
		return (this.producerReviewDetails != null);
	}

	/**
	 * Gets the value of the sharedRecommendationDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.SharedRecommendationStreamEntryRepresentationJAXB }
	 * 
	 */
	public SharedRecommendationStreamEntryRepresentationJAXB getSharedRecommendationDetails() {
		return sharedRecommendationDetails;
	}

	/**
	 * Sets the value of the sharedRecommendationDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.SharedRecommendationStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setSharedRecommendationDetails(SharedRecommendationStreamEntryRepresentationJAXB value) {
		this.sharedRecommendationDetails = value;
	}

	public Boolean isSetSharedRecommendationDetails() {
		return (this.sharedRecommendationDetails != null);
	}

	/**
	 * Gets the value of the productReviewDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProductReviewStreamEntryRepresentationJAXB }
	 * 
	 */
	public ProductReviewStreamEntryRepresentationJAXB getProductReviewDetails() {
		return productReviewDetails;
	}

	/**
	 * Sets the value of the productReviewDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProductReviewStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setProductReviewDetails(ProductReviewStreamEntryRepresentationJAXB value) {
		this.productReviewDetails = value;
	}

	public Boolean isSetProductReviewDetails() {
		return (this.productReviewDetails != null);
	}

	/**
	 * Gets the value of the dealReviewDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.DealReviewStreamEntryRepresentationJAXB }
	 * 
	 */
	public DealReviewStreamEntryRepresentationJAXB getDealReviewDetails() {
		return dealReviewDetails;
	}

	/**
	 * Sets the value of the dealReviewDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.DealReviewStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setDealReviewDetails(DealReviewStreamEntryRepresentationJAXB value) {
		this.dealReviewDetails = value;
	}

	public Boolean isSetDealReviewDetails() {
		return (this.dealReviewDetails != null);
	}

	/**
	 * Gets the value of the smsTrendDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.SMSProductTrendStreamEntryJAXB }
	 * 
	 */
	public SMSProductTrendStreamEntryJAXB getSmsTrendDetails() {
		return smsTrendDetails;
	}

	/**
	 * Sets the value of the smsTrendDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.SMSProductTrendStreamEntryJAXB }
	 * 
	 */
	public void setSmsTrendDetails(SMSProductTrendStreamEntryJAXB value) {
		this.smsTrendDetails = value;
	}

	public Boolean isSetSmsTrendDetails() {
		return (this.smsTrendDetails != null);
	}

	/**
	 * Gets the value of the productBuzzDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProductBuzzDetailsStreamEntryJAXB }
	 * 
	 */
	public ProductBuzzDetailsStreamEntryJAXB getProductBuzzDetails() {
		return productBuzzDetails;
	}

	/**
	 * Sets the value of the productBuzzDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProductBuzzDetailsStreamEntryJAXB }
	 * 
	 */
	public void setProductBuzzDetails(ProductBuzzDetailsStreamEntryJAXB value) {
		this.productBuzzDetails = value;
	}

	public Boolean isSetProductBuzzDetails() {
		return (this.productBuzzDetails != null);
	}

	/**
	 * Gets the value of the producerBuzzDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProducerBuzzDetailsStreamEntryJAXB }
	 * 
	 */
	public ProducerBuzzDetailsStreamEntryJAXB getProducerBuzzDetails() {
		return producerBuzzDetails;
	}

	/**
	 * Sets the value of the producerBuzzDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProducerBuzzDetailsStreamEntryJAXB }
	 * 
	 */
	public void setProducerBuzzDetails(ProducerBuzzDetailsStreamEntryJAXB value) {
		this.producerBuzzDetails = value;
	}

	public Boolean isSetProducerBuzzDetails() {
		return (this.producerBuzzDetails != null);
	}

	/**
	 * Gets the value of the userFollowProducerDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserFollowProducerStreamEntryJAXB }
	 * 
	 */
	public UserFollowProducerStreamEntryJAXB getUserFollowProducerDetails() {
		return userFollowProducerDetails;
	}

	/**
	 * Sets the value of the userFollowProducerDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserFollowProducerStreamEntryJAXB }
	 * 
	 */
	public void setUserFollowProducerDetails(UserFollowProducerStreamEntryJAXB value) {
		this.userFollowProducerDetails = value;
	}

	public Boolean isSetUserFollowProducerDetails() {
		return (this.userFollowProducerDetails != null);
	}

	/**
	 * Gets the value of the userWishProductDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserWishProductStreamEntryJAXB }
	 * 
	 */
	public UserWishProductStreamEntryJAXB getUserWishProductDetails() {
		return userWishProductDetails;
	}

	/**
	 * Sets the value of the userWishProductDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserWishProductStreamEntryJAXB }
	 * 
	 */
	public void setUserWishProductDetails(UserWishProductStreamEntryJAXB value) {
		this.userWishProductDetails = value;
	}

	public Boolean isSetUserWishProductDetails() {
		return (this.userWishProductDetails != null);
	}

	/**
	 * Gets the value of the userTriedProductDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserTriedProductStreamEntryJAXB }
	 * 
	 */
	public UserTriedProductStreamEntryJAXB getUserTriedProductDetails() {
		return userTriedProductDetails;
	}

	/**
	 * Sets the value of the userTriedProductDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserTriedProductStreamEntryJAXB }
	 * 
	 */
	public void setUserTriedProductDetails(UserTriedProductStreamEntryJAXB value) {
		this.userTriedProductDetails = value;
	}

	public Boolean isSetUserTriedProductDetails() {
		return (this.userTriedProductDetails != null);
	}

	/**
	 * Gets the value of the userWishProducerDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserWishProducerStreamEntryJAXB }
	 * 
	 */
	public UserWishProducerStreamEntryJAXB getUserWishProducerDetails() {
		return userWishProducerDetails;
	}

	/**
	 * Sets the value of the userWishProducerDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserWishProducerStreamEntryJAXB }
	 * 
	 */
	public void setUserWishProducerDetails(UserWishProducerStreamEntryJAXB value) {
		this.userWishProducerDetails = value;
	}

	public Boolean isSetUserWishProducerDetails() {
		return (this.userWishProducerDetails != null);
	}

	/**
	 * Gets the value of the userTriedProducerDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserTriedProducerStreamEntryJAXB }
	 * 
	 */
	public UserTriedProducerStreamEntryJAXB getUserTriedProducerDetails() {
		return userTriedProducerDetails;
	}

	/**
	 * Sets the value of the userTriedProducerDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserTriedProducerStreamEntryJAXB }
	 * 
	 */
	public void setUserTriedProducerDetails(UserTriedProducerStreamEntryJAXB value) {
		this.userTriedProducerDetails = value;
	}

	public Boolean isSetUserTriedProducerDetails() {
		return (this.userTriedProducerDetails != null);
	}

	/**
	 * Gets the value of the userGetDealDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserGetDealStreamEntryJAXB }
	 * 
	 */
	public UserGetDealStreamEntryJAXB getUserGetDealDetails() {
		return userGetDealDetails;
	}

	/**
	 * Sets the value of the userGetDealDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserGetDealStreamEntryJAXB }
	 * 
	 */
	public void setUserGetDealDetails(UserGetDealStreamEntryJAXB value) {
		this.userGetDealDetails = value;
	}

	public Boolean isSetUserGetDealDetails() {
		return (this.userGetDealDetails != null);
	}

	/**
	 * Gets the value of the userFollowProductDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserFollowProductStreamEntryJAXB }
	 * 
	 */
	public UserFollowProductStreamEntryJAXB getUserFollowProductDetails() {
		return userFollowProductDetails;
	}

	/**
	 * Sets the value of the userFollowProductDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserFollowProductStreamEntryJAXB }
	 * 
	 */
	public void setUserFollowProductDetails(UserFollowProductStreamEntryJAXB value) {
		this.userFollowProductDetails = value;
	}

	public Boolean isSetUserFollowProductDetails() {
		return (this.userFollowProductDetails != null);
	}

	/**
	 * Gets the value of the userFollowDealDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserFollowDealStreamEntryJAXB }
	 * 
	 */
	public UserFollowDealStreamEntryJAXB getUserFollowDealDetails() {
		return userFollowDealDetails;
	}

	/**
	 * Sets the value of the userFollowDealDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserFollowDealStreamEntryJAXB }
	 * 
	 */
	public void setUserFollowDealDetails(UserFollowDealStreamEntryJAXB value) {
		this.userFollowDealDetails = value;
	}

	public Boolean isSetUserFollowDealDetails() {
		return (this.userFollowDealDetails != null);
	}

	/**
	 * Gets the value of the userFollowDealReviewDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserFollowDealReviewStreamEntryJAXB }
	 * 
	 */
	public UserFollowDealReviewStreamEntryJAXB getUserFollowDealReviewDetails() {
		return userFollowDealReviewDetails;
	}

	/**
	 * Sets the value of the userFollowDealReviewDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserFollowDealReviewStreamEntryJAXB }
	 * 
	 */
	public void setUserFollowDealReviewDetails(UserFollowDealReviewStreamEntryJAXB value) {
		this.userFollowDealReviewDetails = value;
	}

	public Boolean isSetUserFollowDealReviewDetails() {
		return (this.userFollowDealReviewDetails != null);
	}

	/**
	 * Gets the value of the userFollowProducerReviewDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserFollowProducerReviewStreamEntryJAXB }
	 * 
	 */
	public UserFollowProducerReviewStreamEntryJAXB getUserFollowProducerReviewDetails() {
		return userFollowProducerReviewDetails;
	}

	/**
	 * Sets the value of the userFollowProducerReviewDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserFollowProducerReviewStreamEntryJAXB }
	 * 
	 */
	public void setUserFollowProducerReviewDetails(UserFollowProducerReviewStreamEntryJAXB value) {
		this.userFollowProducerReviewDetails = value;
	}

	public Boolean isSetUserFollowProducerReviewDetails() {
		return (this.userFollowProducerReviewDetails != null);
	}

	/**
	 * Gets the value of the userFollowProductReviewDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserFollowProductReviewStreamEntryJAXB }
	 * 
	 */
	public UserFollowProductReviewStreamEntryJAXB getUserFollowProductReviewDetails() {
		return userFollowProductReviewDetails;
	}

	/**
	 * Sets the value of the userFollowProductReviewDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserFollowProductReviewStreamEntryJAXB }
	 * 
	 */
	public void setUserFollowProductReviewDetails(UserFollowProductReviewStreamEntryJAXB value) {
		this.userFollowProductReviewDetails = value;
	}

	public Boolean isSetUserFollowProductReviewDetails() {
		return (this.userFollowProductReviewDetails != null);
	}

	/**
	 * Gets the value of the userCommentProducerReviewDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserCommentProducerReviewStreamEntryJAXB }
	 * 
	 */
	public UserCommentProducerReviewStreamEntryJAXB getUserCommentProducerReviewDetails() {
		return userCommentProducerReviewDetails;
	}

	/**
	 * Sets the value of the userCommentProducerReviewDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserCommentProducerReviewStreamEntryJAXB }
	 * 
	 */
	public void setUserCommentProducerReviewDetails(UserCommentProducerReviewStreamEntryJAXB value) {
		this.userCommentProducerReviewDetails = value;
	}

	public Boolean isSetUserCommentProducerReviewDetails() {
		return (this.userCommentProducerReviewDetails != null);
	}

	/**
	 * Gets the value of the userAddedProducerProductReviewToBoardDetails
	 * property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserAddedProducerProductReviewToBoardStreamEntryJAXB }
	 * 
	 */
	public UserAddedProducerProductReviewToBoardStreamEntryJAXB getUserAddedProducerProductReviewToBoardDetails() {
		return userAddedProducerProductReviewToBoardDetails;
	}

	/**
	 * Sets the value of the userAddedProducerProductReviewToBoardDetails
	 * property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserAddedProducerProductReviewToBoardStreamEntryJAXB }
	 * 
	 */
	public void setUserAddedProducerProductReviewToBoardDetails(UserAddedProducerProductReviewToBoardStreamEntryJAXB value) {
		this.userAddedProducerProductReviewToBoardDetails = value;
	}

	public Boolean isSetUserAddedProducerProductReviewToBoardDetails() {
		return (this.userAddedProducerProductReviewToBoardDetails != null);
	}

	/**
	 * Gets the value of the userCommentProducerProductReviewDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserCommentProducerProductReviewStreamEntryJAXB }
	 * 
	 */
	public UserCommentProducerProductReviewStreamEntryJAXB getUserCommentProducerProductReviewDetails() {
		return userCommentProducerProductReviewDetails;
	}

	/**
	 * Sets the value of the userCommentProducerProductReviewDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserCommentProducerProductReviewStreamEntryJAXB }
	 * 
	 */
	public void setUserCommentProducerProductReviewDetails(UserCommentProducerProductReviewStreamEntryJAXB value) {
		this.userCommentProducerProductReviewDetails = value;
	}

	public Boolean isSetUserCommentProducerProductReviewDetails() {
		return (this.userCommentProducerProductReviewDetails != null);
	}

	/**
	 * Gets the value of the userFollowTagDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserFollowTagStreamEntryJAXB }
	 * 
	 */
	public UserFollowTagStreamEntryJAXB getUserFollowTagDetails() {
		return userFollowTagDetails;
	}

	/**
	 * Sets the value of the userFollowTagDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserFollowTagStreamEntryJAXB }
	 * 
	 */
	public void setUserFollowTagDetails(UserFollowTagStreamEntryJAXB value) {
		this.userFollowTagDetails = value;
	}

	public Boolean isSetUserFollowTagDetails() {
		return (this.userFollowTagDetails != null);
	}

	/**
	 * Gets the value of the userFollowUserDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserFollowUserStreamEntryJAXB }
	 * 
	 */
	public UserFollowUserStreamEntryJAXB getUserFollowUserDetails() {
		return userFollowUserDetails;
	}

	/**
	 * Sets the value of the userFollowUserDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserFollowUserStreamEntryJAXB }
	 * 
	 */
	public void setUserFollowUserDetails(UserFollowUserStreamEntryJAXB value) {
		this.userFollowUserDetails = value;
	}

	public Boolean isSetUserFollowUserDetails() {
		return (this.userFollowUserDetails != null);
	}

	/**
	 * Gets the value of the userFollowUserReviewDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserFollowUserStreamEntryJAXB }
	 * 
	 */
	public UserFollowUserStreamEntryJAXB getUserFollowUserReviewDetails() {
		return userFollowUserReviewDetails;
	}

	/**
	 * Sets the value of the userFollowUserReviewDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserFollowUserStreamEntryJAXB }
	 * 
	 */
	public void setUserFollowUserReviewDetails(UserFollowUserStreamEntryJAXB value) {
		this.userFollowUserReviewDetails = value;
	}

	public Boolean isSetUserFollowUserReviewDetails() {
		return (this.userFollowUserReviewDetails != null);
	}

	/**
	 * Gets the value of the userRewardStreamEntryJAXB property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserRewardStreamEntryJAXB }
	 * 
	 */
	public UserRewardStreamEntryJAXB getUserRewardStreamEntryJAXB() {
		return userRewardStreamEntryJAXB;
	}

	/**
	 * Sets the value of the userRewardStreamEntryJAXB property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserRewardStreamEntryJAXB }
	 * 
	 */
	public void setUserRewardStreamEntryJAXB(UserRewardStreamEntryJAXB value) {
		this.userRewardStreamEntryJAXB = value;
	}

	public Boolean isSetUserRewardStreamEntryJAXB() {
		return (this.userRewardStreamEntryJAXB != null);
	}

	/**
	 * Gets the value of the userBadgeStreamEntryJAXB property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserBadgeStreamEntryJAXB }
	 * 
	 */
	public UserBadgeStreamEntryJAXB getUserBadgeStreamEntryJAXB() {
		return userBadgeStreamEntryJAXB;
	}

	/**
	 * Sets the value of the userBadgeStreamEntryJAXB property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserBadgeStreamEntryJAXB }
	 * 
	 */
	public void setUserBadgeStreamEntryJAXB(UserBadgeStreamEntryJAXB value) {
		this.userBadgeStreamEntryJAXB = value;
	}

	public Boolean isSetUserBadgeStreamEntryJAXB() {
		return (this.userBadgeStreamEntryJAXB != null);
	}

	/**
	 * Gets the value of the producerLandingPageDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProducerLandingPageStreamEntryRepresentationJAXB }
	 * 
	 */
	public ProducerLandingPageStreamEntryRepresentationJAXB getProducerLandingPageDetails() {
		return producerLandingPageDetails;
	}

	/**
	 * Sets the value of the producerLandingPageDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProducerLandingPageStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setProducerLandingPageDetails(ProducerLandingPageStreamEntryRepresentationJAXB value) {
		this.producerLandingPageDetails = value;
	}

	public Boolean isSetProducerLandingPageDetails() {
		return (this.producerLandingPageDetails != null);
	}

	/**
	 * Gets the value of the producerProductLandingPageDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProducerProductLandingPageEntryRepresentationJAXB }
	 * 
	 */
	public ProducerProductLandingPageEntryRepresentationJAXB getProducerProductLandingPageDetails() {
		return producerProductLandingPageDetails;
	}

	/**
	 * Sets the value of the producerProductLandingPageDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProducerProductLandingPageEntryRepresentationJAXB }
	 * 
	 */
	public void setProducerProductLandingPageDetails(ProducerProductLandingPageEntryRepresentationJAXB value) {
		this.producerProductLandingPageDetails = value;
	}

	public Boolean isSetProducerProductLandingPageDetails() {
		return (this.producerProductLandingPageDetails != null);
	}

	/**
	 * Gets the value of the producerProductDetailsExtended property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProducerProductEntryExtendedRepresentationJAXB }
	 * 
	 */
	public ProducerProductEntryExtendedRepresentationJAXB getProducerProductDetailsExtended() {
		return producerProductDetailsExtended;
	}

	/**
	 * Sets the value of the producerProductDetailsExtended property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProducerProductEntryExtendedRepresentationJAXB }
	 * 
	 */
	public void setProducerProductDetailsExtended(ProducerProductEntryExtendedRepresentationJAXB value) {
		this.producerProductDetailsExtended = value;
	}

	public Boolean isSetProducerProductDetailsExtended() {
		return (this.producerProductDetailsExtended != null);
	}

	/**
	 * Gets the value of the producerDetailsExtended property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProducerEntryExtendedRepresentationJAXB }
	 * 
	 */
	public ProducerEntryExtendedRepresentationJAXB getProducerDetailsExtended() {
		return producerDetailsExtended;
	}

	/**
	 * Sets the value of the producerDetailsExtended property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProducerEntryExtendedRepresentationJAXB }
	 * 
	 */
	public void setProducerDetailsExtended(ProducerEntryExtendedRepresentationJAXB value) {
		this.producerDetailsExtended = value;
	}

	public Boolean isSetProducerDetailsExtended() {
		return (this.producerDetailsExtended != null);
	}

	/**
	 * Gets the value of the producerProductReviewDetailsExtended property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.ProducerProductReviewExtendedStreamEntryRepresentationJAXB }
	 * 
	 */
	public ProducerProductReviewExtendedStreamEntryRepresentationJAXB getProducerProductReviewDetailsExtended() {
		return producerProductReviewDetailsExtended;
	}

	/**
	 * Sets the value of the producerProductReviewDetailsExtended property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.ProducerProductReviewExtendedStreamEntryRepresentationJAXB }
	 * 
	 */
	public void setProducerProductReviewDetailsExtended(ProducerProductReviewExtendedStreamEntryRepresentationJAXB value) {
		this.producerProductReviewDetailsExtended = value;
	}

	public Boolean isSetProducerProductReviewDetailsExtended() {
		return (this.producerProductReviewDetailsExtended != null);
	}

	/**
	 * Gets the value of the fmRecommendation property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.FMRecommendationEntryRepresentationJAXB }
	 * 
	 */
	public FMRecommendationEntryRepresentationJAXB getFMRecommendation() {
		return fmRecommendation;
	}

	/**
	 * Sets the value of the fmRecommendation property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.FMRecommendationEntryRepresentationJAXB }
	 * 
	 */
	public void setFMRecommendation(FMRecommendationEntryRepresentationJAXB value) {
		this.fmRecommendation = value;
	}

	public Boolean isSetFMRecommendation() {
		return (this.fmRecommendation != null);
	}

	/**
	 * Gets the value of the userBoardDetailsExtended property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserBoardStreamEntryExtendedJAXB }
	 * 
	 */
	public UserBoardStreamEntryExtendedJAXB getUserBoardDetailsExtended() {
		return userBoardDetailsExtended;
	}

	/**
	 * Sets the value of the userBoardDetailsExtended property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserBoardStreamEntryExtendedJAXB }
	 * 
	 */
	public void setUserBoardDetailsExtended(UserBoardStreamEntryExtendedJAXB value) {
		this.userBoardDetailsExtended = value;
	}

	public Boolean isSetUserBoardDetailsExtended() {
		return (this.userBoardDetailsExtended != null);
	}

	/**
	 * Gets the value of the userBoardDetails property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.UserBoardStreamEntryJAXB }
	 * 
	 */
	public UserBoardStreamEntryJAXB getUserBoardDetails() {
		return userBoardDetails;
	}

	/**
	 * Sets the value of the userBoardDetails property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.UserBoardStreamEntryJAXB }
	 * 
	 */
	public void setUserBoardDetails(UserBoardStreamEntryJAXB value) {
		this.userBoardDetails = value;
	}

	public Boolean isSetUserBoardDetails() {
		return (this.userBoardDetails != null);
	}

	/**
	 * Gets the value of the streamInformation property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.StreamInformationRepresentationJAXB }
	 * 
	 */
	public StreamInformationRepresentationJAXB getStreamInformation() {
		return streamInformation;
	}

	/**
	 * Sets the value of the streamInformation property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.StreamInformationRepresentationJAXB }
	 * 
	 */
	public void setStreamInformation(StreamInformationRepresentationJAXB value) {
		this.streamInformation = value;
	}

	public Boolean isSetStreamInformation() {
		return (this.streamInformation != null);
	}

	/**
	 * Gets the value of the look property.
	 * 
	 * @return possible object is
	 *         {@link com.ubiquity.common.jaxb.stream.FashionLookJAXB }
	 * 
	 */
	public FashionLookJAXB getLook() {
		return look;
	}

	/**
	 * Sets the value of the look property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link com.ubiquity.common.jaxb.stream.FashionLookJAXB }
	 * 
	 */
	public void setLook(FashionLookJAXB value) {
		this.look = value;
	}

	public Boolean isSetLook() {
		return (this.look != null);
	}

	public EcommerceProductJAXB getEcommerceProductJAXB() {
		return ecommerceProductJAXB;
	}

	public void setEcommerceProductJAXB(EcommerceProductJAXB ecommerceProductJAXB) {
		this.ecommerceProductJAXB = ecommerceProductJAXB;
	}

	public UserFollowFashionLookStreamEntryJAXB getUserFollowLookDetails() {
		return userFollowLookDetails;
	}

	public void setUserFollowLookDetails(UserFollowFashionLookStreamEntryJAXB userFollowLookDetails) {
		this.userFollowLookDetails = userFollowLookDetails;
	}
	/*
	 * 
	 * // public LookUserDetailJAXB getLookUserDetail() { // return
	 * lookUserDetail; // } // // public void
	 * setLookUserDetail(LookUserDetailJAXB lookUserDetail) { //
	 * this.lookUserDetail = lookUserDetail; // }
	 */

	public EcommerceStoreJAXB getEcommerceStoreJAXB() {
		return ecommerceStoreJAXB;
	}

	public void setEcommerceStoreJAXB(EcommerceStoreJAXB ecommerceStoreJAXB) {
		this.ecommerceStoreJAXB = ecommerceStoreJAXB;
	}

	public FashionLookCommonJAXB getLookCommonJAXB() {
		return lookCommonJAXB;
	}

	public void setLookCommonJAXB(FashionLookCommonJAXB lookCommonJAXB) {
		this.lookCommonJAXB = lookCommonJAXB;
	}
	/*
	 * 
	 * public StreamUserDetailJAXB getStreamUserDetail() { return
	 * streamUserDetail; }
	 * 
	 * public void setStreamUserDetail(StreamUserDetailJAXB streamUserDetail) {
	 * this.streamUserDetail = streamUserDetail; }
	 */

	public ThemeCollectionDetailsJAXB getThemeCollectionDetailsJAXB() {
		return themeCollectionDetailsJAXB;
	}

	public void setThemeCollectionDetailsJAXB(ThemeCollectionDetailsJAXB themeCollectionDetailsJAXB) {
		this.themeCollectionDetailsJAXB = themeCollectionDetailsJAXB;
	}

	// public ThemeCollectionJAXB getThemeCollectionJAXB() {
	// return themeCollectionJAXB;
	// }

	// public void setThemeCollectionJAXB(ThemeCollectionJAXB
	// themeCollectionJAXB) {
	// this.themeCollectionJAXB = themeCollectionJAXB;
	// }

	public CollegeCampusJAXB getCollegeCampusJAXB() {
		return collegeCampusJAXB;
	}

	public void setCollegeCampusJAXB(CollegeCampusJAXB collegeCampusJAXB) {
		this.collegeCampusJAXB = collegeCampusJAXB;
	}

	public SearchFacetJAXB getSearchFacetJAXB() {
		return searchFacetJAXB;
	}

	public void setSearchFacetJAXB(SearchFacetJAXB searchFacetJAXB) {
		this.searchFacetJAXB = searchFacetJAXB;
	}

	public ContentJAXB getContentJAXB() {
		return contentJAXB;
	}

	public void setContentJAXB(ContentJAXB contentJAXB) {
		this.contentJAXB = contentJAXB;
	}

	public CollateApisPaginationJAXB getCollateApisPaginationJAXB() {
		return collateApisPaginationJAXB;
	}

	public void setCollateApisPaginationJAXB(CollateApisPaginationJAXB collateApisPaginationJAXB) {
		this.collateApisPaginationJAXB = collateApisPaginationJAXB;
	}

	public CampaignJAXB getCampaignJAXB() {
		return campaignJAXB;
	}

	public void setCampaignJAXB(CampaignJAXB campaignJAXB) {
		this.campaignJAXB = campaignJAXB;
	}

	public CampaignLimitedJAXB getCampaignLimitedJAXB() {
		return campaignLimitedJAXB;
	}

	public void setCampaignLimitedJAXB(CampaignLimitedJAXB campaignLimitedJAXB) {
		this.campaignLimitedJAXB = campaignLimitedJAXB;
	}

	public GroupJAXB getGroupJAXB() {
		return groupJAXB;
	}

	public void setGroupJAXB(GroupJAXB groupJAXB) {
		this.groupJAXB = groupJAXB;
	}

	public EcommerceProductFullJAXB getEcommerceProductFullJAXB() {
		return ecommerceProductFullJAXB;
	}

	public void setEcommerceProductFullJAXB(EcommerceProductFullJAXB ecommerceProductFullJAXB) {
		this.ecommerceProductFullJAXB = ecommerceProductFullJAXB;
	}

	public AppCardsJAXB getAppCardsJAXB() {
		return appCardsJAXB;
	}

	public void setAppCardsJAXB(AppCardsJAXB appCardsJAXB) {
		this.appCardsJAXB = appCardsJAXB;
	}

	public String getLookContext() {
		return lookContext;
	}

	public void setLookContext(String lookContext) {
		this.lookContext = lookContext;
	}

	public ECommOrderTransactionJAXB getEcommOrderTransactionJAXB() {
		return ecommOrderTransactionJAXB;
	}

	public void setEcommOrderTransactionJAXB(ECommOrderTransactionJAXB ecommOrderTransactionJAXB) {
		this.ecommOrderTransactionJAXB = ecommOrderTransactionJAXB;
	}

	public ReactionJAXB getReactionJAXB() {
		return reactionJAXB;
	}

	public void setReactionJAXB(ReactionJAXB reactionJAXB) {
		this.reactionJAXB = reactionJAXB;
	}

	public FlippingCardJAXB getFlippingCardJAXB() {
		return flippingCardJAXB;
	}

	public void setFlippingCardJAXB(FlippingCardJAXB flippingCardJAXB) {
		this.flippingCardJAXB = flippingCardJAXB;

	}

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;

		GenericStreamEntry that = (GenericStreamEntry) o;

		if (ecommerceProductJAXB != null ? !ecommerceProductJAXB.equals(that.ecommerceProductJAXB) : that.ecommerceProductJAXB != null)
			return false;
		if (entrytype != null ? !entrytype.equals(that.entrytype) : that.entrytype != null)
			return false;

		if (lookCommonJAXB != null ? !lookCommonJAXB.equals(that.lookCommonJAXB) : that.lookCommonJAXB != null)
			return false;
		// if (producerReviewDetails != null ?
		// !producerReviewDetails.equals(that.producerReviewDetails) :
		// that.producerReviewDetails != null)
		// return false;
		if (productReviewDetails != null ? !productReviewDetails.equals(that.productReviewDetails) : that.productReviewDetails != null)
			return false;
		if (themeCollectionDetailsJAXB != null ? !themeCollectionDetailsJAXB.equals(that.themeCollectionDetailsJAXB) : that.themeCollectionDetailsJAXB != null)
			return false;
		// if (themeCollectionJAXB != null ?
		// !themeCollectionJAXB.equals(that.themeCollectionJAXB) :
		// that.themeCollectionJAXB != null)
		// return false;
		// if (userCommentProducerProductReviewDetails != null ?
		// !userCommentProducerProductReviewDetails.equals(that.userCommentProducerProductReviewDetails)
		// : that.userCommentProducerProductReviewDetails != null)
		// return false;
		// if (userCommentProducerReviewDetails != null ?
		// !userCommentProducerReviewDetails.equals(that.userCommentProducerReviewDetails)
		// : that.userCommentProducerReviewDetails != null)
		// return false;mm
		// if (userDetails != null ? !userDetails.equals(that.userDetails) :
		// that.userDetails != null) return false;
		if (userFollowLookDetails != null ? !userFollowLookDetails.equals(that.userFollowLookDetails) : that.userFollowLookDetails != null)
			return false;
		if (ecommOrderTransactionJAXB != null ? !ecommOrderTransactionJAXB.equals(that.ecommOrderTransactionJAXB) : that.ecommOrderTransactionJAXB != null)
			return false;
		//
		// if (userFollowProducerDetails != null ?
		// !userFollowProducerDetails.equals(that.userFollowProducerDetails) :
		// that.userFollowProducerDetails != null)
		// return false;
		// if (userFollowProducerReviewDetails != null ?
		// !userFollowProducerReviewDetails.equals(that.userFollowProducerReviewDetails)
		// : that.userFollowProducerReviewDetails != null)
		// return false;
		// if (userFollowProductReviewDetails != null ?
		// !userFollowProductReviewDetails.equals(that.userFollowProductReviewDetails)
		// : that.userFollowProductReviewDetails != null)
		// return false;
		// if (userFollowUserDetails != null ?
		// !userFollowUserDetails.equals(that.userFollowUserDetails) :
		// that.userFollowUserDetails != null)
		// return false;

		return true;
	}

	public VotecardJAXB getVotecardJAXB() {
		return votecardJAXB;
	}

	public void setVotecardJAXB(VotecardJAXB votecardJAXB) {
		this.votecardJAXB = votecardJAXB;
	}

	public Long getUpdateTimestamp() {
		return updateTimestamp;
	}

	public void setUpdateTimestamp(Long updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

	@Override
	public int hashCode() {
		int result = entrytype != null ? entrytype.hashCode() : 0;
		// result = 31 * result + (userDetails != null ? userDetails.hashCode()
		// : 0);
		// result = 31 * result + (producerReviewDetails != null ?
		// producerReviewDetails.hashCode() : 0);
		result = 31 * result + (productReviewDetails != null ? productReviewDetails.hashCode() : 0);
		// result = 31 * result + (userFollowProducerDetails != null ?
		// userFollowProducerDetails.hashCode() : 0);
		// result = 31 * result + (userFollowProducerReviewDetails != null ?
		// userFollowProducerReviewDetails.hashCode() : 0);
		// result = 31 * result + (userFollowProductReviewDetails != null ?
		// userFollowProductReviewDetails.hashCode() : 0);
		result = 31 * result + (userFollowLookDetails != null ? userFollowLookDetails.hashCode() : 0);
		// result = 31 * result + (userCommentProducerReviewDetails != null ?
		// userCommentProducerReviewDetails.hashCode() : 0);
		// result = 31 * result + (userCommentProducerProductReviewDetails !=
		// null ? userCommentProducerProductReviewDetails.hashCode() : 0);
		// result = 31 * result + (userFollowUserDetails != null ?
		// userFollowUserDetails.hashCode() : 0);
		result = 31 * result + (lookCommonJAXB != null ? lookCommonJAXB.hashCode() : 0);
		result = 31 * result + (ecommerceProductJAXB != null ? ecommerceProductJAXB.hashCode() : 0);
		// result = 31 * result + (themeCollectionJAXB != null ?
		// themeCollectionJAXB.hashCode() : 0);
		result = 31 * result + (themeCollectionDetailsJAXB != null ? themeCollectionDetailsJAXB.hashCode() : 0);
		return result;
	}

	public int compareTo(GenericStreamEntry arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	/*@Override
	public int compareTo(GenericStreamEntry o) {
		return o.updateTimestamp.compareTo(this.updateTimestamp);
	}*/

}
