//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.11 at 01:55:25 PM IST 
//


package com.ubiquity.common.jaxb.stream;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for StreamUserDetailJAXB complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StreamUserDetailJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userLName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isRegistered" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *         &lt;element name="isPrivateUser" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *         &lt;element name="isLoggedInUserFollowingUser" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *         &lt;element name="isLoggedInUserFollowedByUser" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *         &lt;element name="userCommentSettings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="webLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="facebookLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="twitterLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createdDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lovesReceived" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="followerCount" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="followingCount" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="recommendationCount" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="imageDetails" type="{}StreamImageDetailsJAXB"/>
 *         &lt;element name="needCacheSyncUp" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LookUserDetailJAXB", propOrder = {
        "userId",
        "userName",
        "userCommentsSetting",
        "isPrivateUser",
        "isLoggedInUserFollowingUser",
        "isLoggedInUserFollowedByUser",
        "imageUpdateDate",
        "image_pid",
        "needCacheSyncUp",
        "isVerified",
        "blogUrl",
        "status",
        "profileType",
        "isOfficial",
        "handle",
        "showImage",
        "gender",
        "status"
})
@XmlRootElement public class LookUserDetailJAXB
        implements Serializable
{

    private final static Long serialVersionUID = 12343L;
    @XmlElement(required = true)
    protected Long userId;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = false)
    protected String userCommentsSetting;
    @XmlElement(required = true)
    protected Boolean isPrivateUser;
    @XmlElement(required = false)
    protected Boolean isLoggedInUserFollowingUser;
    @XmlElement(required = false)
    protected Boolean isLoggedInUserFollowedByUser;
    @XmlElement(required = false)
    protected String image_pid;
    @XmlElement(required = false)
    protected Long imageUpdateDate;
    @XmlElement(required = false)
   // protected StreamImageDetailsJAXB imageDetails;
    protected Boolean needCacheSyncUp;
    protected Boolean isVerified;

    protected String blogUrl;

    protected String profileType;

    protected Boolean isOfficial;
    protected String handle;
    @XmlElement(defaultValue = "true")
    protected Boolean showImage;
    protected String gender;
    protected String status;


    /**
     * Gets the value of the userId property.
     *
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     *
     */
    public void setUserId(Long value) {
        this.userId = value;
    }

    public Boolean isSetUserId() {
        return true;
    }

    /**
     * Gets the value of the userName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    public Boolean isSetUserName() {
        return (this.userName!= null);
    }


    public Boolean isSetIsRegistered() {
        return true;
    }

    /**
     * Gets the value of the isPrivateUser property.
     *
     */
    public Boolean isIsPrivateUser() {
        return isPrivateUser;
    }

    /**
     * Sets the value of the isPrivateUser property.
     *
     */
    public void setIsPrivateUser(Boolean value) {
        this.isPrivateUser = value;
    }

    public Boolean isSetIsPrivateUser() {
        return true;
    }

    /**
     * Gets the value of the isLoggedInUserFollowingUser property.
     *
     */
    public Boolean isIsLoggedInUserFollowingUser() {
        return isLoggedInUserFollowingUser;
    }

    /**
     * Sets the value of the isLoggedInUserFollowingUser property.
     *
     */
    public void setIsLoggedInUserFollowingUser(Boolean value) {
        this.isLoggedInUserFollowingUser = value;
    }

    public Boolean isSetIsLoggedInUserFollowingUser() {
        return true;
    }

    /**
     * Gets the value of the isLoggedInUserFollowedByUser property.
     *
     */
    public Boolean isIsLoggedInUserFollowedByUser() {
        return isLoggedInUserFollowedByUser;
    }

    /**
     * Sets the value of the isLoggedInUserFollowedByUser property.
     *
     */
    public void setIsLoggedInUserFollowedByUser(Boolean value) {
        this.isLoggedInUserFollowedByUser = value;
    }

    public Boolean isSetIsLoggedInUserFollowedByUser() {
        return true;
    }

    public Long getImageUpdateDate() {
        return imageUpdateDate;
    }

    public void setImageUpdateDate(Long imageUpdateDate) {
        this.imageUpdateDate = imageUpdateDate;
    }

    /**
     * Gets the value of the needCacheSyncUp property.
     *
     */
    public Boolean isNeedCacheSyncUp() {
        return needCacheSyncUp;
    }

    /**
     * Sets the value of the needCacheSyncUp property.
     *
     */
    public void setNeedCacheSyncUp(Boolean value) {
        this.needCacheSyncUp = value;
    }

    public Boolean isSetNeedCacheSyncUp() {
        return true;
    }

    public String getImage_pid() {
        return image_pid;
    }

    public void setImage_pid(String image_pid) {
        this.image_pid = image_pid;
    }

    public String getUserCommentsSetting() {
        return userCommentsSetting;
    }

    public void setUserCommentsSetting(String userCommentsSetting) {
        this.userCommentsSetting = userCommentsSetting;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

    public String getBlogUrl() {
        return blogUrl;
    }

    public void setBlogUrl(String blogUrl) {
        this.blogUrl = blogUrl;
    }

    public String getProfileType() {
        return profileType;
    }

    public void setProfileType(String profileType) {
        this.profileType = profileType;
    }

    public Boolean getIsOfficial() {
        return isOfficial;
    }

    public void setIsOfficial(Boolean isOfficial) {
        this.isOfficial = isOfficial;
    }

    public String getHandle() {
        return handle;
    }

    public void setHandle(String handle) {
        this.handle = handle;
    }

    public Boolean getShowImage() {
        return showImage;
    }

    public void setShowImage(Boolean showImage) {
        this.showImage = showImage;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        LookUserDetailJAXB that = (LookUserDetailJAXB) o;

        if (isPrivateUser != null ? !isPrivateUser.equals(that.isPrivateUser) : that.isPrivateUser != null)
            return false;
        if (userId != null ? !userId.equals(that.userId) : that.userId != null) return false;
        if (userName != null ? !userName.equals(that.userName) : that.userName != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = userId != null ? userId.hashCode() : 0;
        result = 31 * result + (userName != null ? userName.hashCode() : 0);
        result = 31 * result + (isPrivateUser != null ? isPrivateUser.hashCode() : 0);
        return result;
    }
}
