//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.11 at 01:55:25 PM IST 
//


package com.ubiquity.common.jaxb.stream;

import java.io.Serializable;
import java.util.Date;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ProducerBuzzDetailsStreamEntryJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProducerBuzzDetailsStreamEntryJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contactId" type="{}StreamUserDetailJAXB"/>
 *         &lt;element name="entrytype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="payload" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="producerDetails" type="{}StreamProducerDetailJAXB"/>
 *         &lt;element name="branchDetails" type="{}StreamProducerBranchDetailJAXB"/>
 *         &lt;element name="userRating" type="{}userRatingDetailJAXB"/>
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="reviewView" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProducerBuzzDetailsStreamEntryJAXB", propOrder = {
    "contactId",
    "entrytype",
    "weight",
    "timestamp",
    "payload",
    "producerDetails",
    "branchDetails",
    "userRating",
    "createDate",
    "reviewView"
})
@XmlRootElement public class ProducerBuzzDetailsStreamEntryJAXB
    implements Serializable
{

    private final static Long serialVersionUID = 12343L;
    @XmlElement(required = true)
    protected StreamUserDetailJAXB contactId;
    @XmlElement(required = true)
    protected String entrytype;
    protected Long weight;
    protected Long timestamp;
    @XmlElement(required = true)
    protected String payload;
    @XmlElement(required = true)
    protected StreamProducerDetailJAXB producerDetails;
    @XmlElement(required = true)
    protected StreamProducerBranchDetailJAXB branchDetails;
    @XmlElement(required = true)
    protected UserRatingDetailJAXB userRating;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date createDate;
    protected Long reviewView;

    /**
     * Gets the value of the contactId property.
     * 
     * @return
     *     possible object is
     *     {@link StreamUserDetailJAXB }
     *     
     */
    public StreamUserDetailJAXB getContactId() {
        return contactId;
    }

    /**
     * Sets the value of the contactId property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamUserDetailJAXB }
     *     
     */
    public void setContactId(StreamUserDetailJAXB value) {
        this.contactId = value;
    }

    public Boolean isSetContactId() {
        return (this.contactId!= null);
    }

    /**
     * Gets the value of the entrytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntrytype() {
        return entrytype;
    }

    /**
     * Sets the value of the entrytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntrytype(String value) {
        this.entrytype = value;
    }

    public Boolean isSetEntrytype() {
        return (this.entrytype!= null);
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(Long value) {
        this.weight = value;
    }

    public Boolean isSetWeight() {
        return true;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     */
    public void setTimestamp(Long value) {
        this.timestamp = value;
    }

    public Boolean isSetTimestamp() {
        return true;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayload(String value) {
        this.payload = value;
    }

    public Boolean isSetPayload() {
        return (this.payload!= null);
    }

    /**
     * Gets the value of the producerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link StreamProducerDetailJAXB }
     *     
     */
    public StreamProducerDetailJAXB getProducerDetails() {
        return producerDetails;
    }

    /**
     * Sets the value of the producerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamProducerDetailJAXB }
     *     
     */
    public void setProducerDetails(StreamProducerDetailJAXB value) {
        this.producerDetails = value;
    }

    public Boolean isSetProducerDetails() {
        return (this.producerDetails!= null);
    }

    /**
     * Gets the value of the branchDetails property.
     * 
     * @return
     *     possible object is
     *     {@link StreamProducerBranchDetailJAXB }
     *     
     */
    public StreamProducerBranchDetailJAXB getBranchDetails() {
        return branchDetails;
    }

    /**
     * Sets the value of the branchDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamProducerBranchDetailJAXB }
     *     
     */
    public void setBranchDetails(StreamProducerBranchDetailJAXB value) {
        this.branchDetails = value;
    }

    public Boolean isSetBranchDetails() {
        return (this.branchDetails!= null);
    }

    /**
     * Gets the value of the userRating property.
     * 
     * @return
     *     possible object is
     *     {@link UserRatingDetailJAXB }
     *     
     */
    public UserRatingDetailJAXB getUserRating() {
        return userRating;
    }

    /**
     * Sets the value of the userRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserRatingDetailJAXB }
     *     
     */
    public void setUserRating(UserRatingDetailJAXB value) {
        this.userRating = value;
    }

    public Boolean isSetUserRating() {
        return (this.userRating!= null);
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateDate(Date value) {
        this.createDate = value;
    }

    public Boolean isSetCreateDate() {
        return (this.createDate!= null);
    }

    /**
     * Gets the value of the reviewView property.
     * 
     */
    public Long getReviewView() {
        return reviewView;
    }

    /**
     * Sets the value of the reviewView property.
     * 
     */
    public void setReviewView(Long value) {
        this.reviewView = value;
    }

    public Boolean isSetReviewView() {
        return true;
    }

}
