//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.11 at 01:55:25 PM IST 
//


package com.ubiquity.common.jaxb.stream;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ProducerStreamEntryRepresentationJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProducerStreamEntryRepresentationJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="entrytype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="producerId" type="{http://www.w3.org/2001/XMLSchema}Long" minOccurs="0"/>
 *         &lt;element name="producerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="storeCount" type="{http://www.w3.org/2001/XMLSchema}Integer" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}Integer" minOccurs="0"/>
 *         &lt;element name="productCount" type="{http://www.w3.org/2001/XMLSchema}Integer" minOccurs="0"/>
 *         &lt;element name="followers" type="{http://www.w3.org/2001/XMLSchema}Integer" minOccurs="0"/>
 *         &lt;element name="recommendations" type="{http://www.w3.org/2001/XMLSchema}Integer" minOccurs="0"/>
 *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="facebookHandle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="twitterHandle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="producerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="storeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isUserFollowing" type="{http://www.w3.org/2001/XMLSchema}Boolean" minOccurs="0"/>
 *         &lt;element name="storeImageDetails" type="{}StreamImageDetailsJAXB"/>
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="imageDetails" type="{}StreamImageDetailsJAXB"/>
 *         &lt;element name="userAdded" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *         &lt;element name="sourceUser" type="{}StreamUserDetailJAXB"/>
 *         &lt;element name="ownerUser" type="{}StreamUserDetailJAXB"/>
 *         &lt;element name="likes" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="reviews" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="tags" type="{}StreamTagsDetailJAXB" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="branches" type="{}StreamProducerBranchDetailJAXB" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="categories" type="{}StreamTagsDetailJAXB" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProducerStreamEntryRepresentationJAXB", propOrder = {
    "id",
    "entrytype",
    "weight",
    "timestamp",
    "name",
    "producerId",
    "producerCode",
    "storeCount",
    "type",
    "productCount",
    "followers",
    "recommendations",
    "website",
    "contactEmail",
    "contactNumber",
    "facebookHandle",
    "twitterHandle",
    "producerName",
    "desc",
    "storeType",
    "isUserFollowing",
    "storeImageDetails",
    "createDate",
    "imageDetails",
    "userAdded",
    "sourceUser",
    "ownerUser",
    "likes",
    "comments",
    "reviews",
    "tags",
    "branches",
    "categories"
})
@XmlSeeAlso({
    ProducerEntryExtendedRepresentationJAXB.class
})
@XmlRootElement public class ProducerStreamEntryRepresentationJAXB
    implements Serializable
{

    private final static Long serialVersionUID = 12343L;
    protected Long id;
    @XmlElement(required = true)
    protected String entrytype;
    protected Long weight;
    protected Long timestamp;
    @XmlElement(required = true)
    protected String name;
    protected Long producerId;
    @XmlElement(required = true)
    protected String producerCode;
    protected Integer storeCount;
    protected Integer type;
    protected Integer productCount;
    protected Integer followers;
    protected Integer recommendations;
    protected String website;
    protected String contactEmail;
    protected String contactNumber;
    protected String facebookHandle;
    protected String twitterHandle;
    protected String producerName;
    protected String desc;
    protected String storeType;
    protected Boolean isUserFollowing;
    @XmlElement(required = true)
    protected StreamImageDetailsJAXB storeImageDetails;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date createDate;
    @XmlElement(required = true)
    protected StreamImageDetailsJAXB imageDetails;
    protected Boolean userAdded;
    @XmlElement(required = true)
    protected StreamUserDetailJAXB sourceUser;
    @XmlElement(required = true)
    protected StreamUserDetailJAXB ownerUser;
    protected Long likes;
    protected Long comments;
    protected Long reviews;
    @XmlElement(nillable = true)
    protected List<StreamTagsDetailJAXB> tags;
    @XmlElement(nillable = true)
    protected List<StreamProducerBranchDetailJAXB> branches;
    @XmlElement(nillable = true)
    protected List<StreamTagsDetailJAXB> categories;

    /**
     * Gets the value of the id property.
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(Long value) {
        this.id = value;
    }

    public Boolean isSetId() {
        return true;
    }

    /**
     * Gets the value of the entrytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntrytype() {
        return entrytype;
    }

    /**
     * Sets the value of the entrytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntrytype(String value) {
        this.entrytype = value;
    }

    public Boolean isSetEntrytype() {
        return (this.entrytype!= null);
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(Long value) {
        this.weight = value;
    }

    public Boolean isSetWeight() {
        return true;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     */
    public void setTimestamp(Long value) {
        this.timestamp = value;
    }

    public Boolean isSetTimestamp() {
        return true;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public Boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the producerId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getProducerId() {
        return producerId;
    }

    /**
     * Sets the value of the producerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProducerId(Long value) {
        this.producerId = value;
    }

    public Boolean isSetProducerId() {
        return (this.producerId!= null);
    }

    /**
     * Gets the value of the producerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerCode() {
        return producerCode;
    }

    /**
     * Sets the value of the producerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerCode(String value) {
        this.producerCode = value;
    }

    public Boolean isSetProducerCode() {
        return (this.producerCode!= null);
    }

    /**
     * Gets the value of the storeCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStoreCount() {
        return storeCount;
    }

    /**
     * Sets the value of the storeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStoreCount(Integer value) {
        this.storeCount = value;
    }

    public Boolean isSetStoreCount() {
        return (this.storeCount!= null);
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setType(Integer value) {
        this.type = value;
    }

    public Boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the productCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * Sets the value of the productCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProductCount(Integer value) {
        this.productCount = value;
    }

    public Boolean isSetProductCount() {
        return (this.productCount!= null);
    }

    /**
     * Gets the value of the followers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFollowers() {
        return followers;
    }

    /**
     * Sets the value of the followers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFollowers(Integer value) {
        this.followers = value;
    }

    public Boolean isSetFollowers() {
        return (this.followers!= null);
    }

    /**
     * Gets the value of the recommendations property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRecommendations() {
        return recommendations;
    }

    /**
     * Sets the value of the recommendations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRecommendations(Integer value) {
        this.recommendations = value;
    }

    public Boolean isSetRecommendations() {
        return (this.recommendations!= null);
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    public Boolean isSetWebsite() {
        return (this.website!= null);
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail(String value) {
        this.contactEmail = value;
    }

    public Boolean isSetContactEmail() {
        return (this.contactEmail!= null);
    }

    /**
     * Gets the value of the contactNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * Sets the value of the contactNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactNumber(String value) {
        this.contactNumber = value;
    }

    public Boolean isSetContactNumber() {
        return (this.contactNumber!= null);
    }

    /**
     * Gets the value of the facebookHandle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacebookHandle() {
        return facebookHandle;
    }

    /**
     * Sets the value of the facebookHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacebookHandle(String value) {
        this.facebookHandle = value;
    }

    public Boolean isSetFacebookHandle() {
        return (this.facebookHandle!= null);
    }

    /**
     * Gets the value of the twitterHandle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTwitterHandle() {
        return twitterHandle;
    }

    /**
     * Sets the value of the twitterHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTwitterHandle(String value) {
        this.twitterHandle = value;
    }

    public Boolean isSetTwitterHandle() {
        return (this.twitterHandle!= null);
    }

    /**
     * Gets the value of the producerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerName() {
        return producerName;
    }

    /**
     * Sets the value of the producerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerName(String value) {
        this.producerName = value;
    }

    public Boolean isSetProducerName() {
        return (this.producerName!= null);
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    public Boolean isSetDesc() {
        return (this.desc!= null);
    }

    /**
     * Gets the value of the storeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreType() {
        return storeType;
    }

    /**
     * Sets the value of the storeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreType(String value) {
        this.storeType = value;
    }

    public Boolean isSetStoreType() {
        return (this.storeType!= null);
    }

    /**
     * Gets the value of the isUserFollowing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsUserFollowing() {
        return isUserFollowing;
    }

    /**
     * Sets the value of the isUserFollowing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsUserFollowing(Boolean value) {
        this.isUserFollowing = value;
    }

    public Boolean isSetIsUserFollowing() {
        return (this.isUserFollowing!= null);
    }

    /**
     * Gets the value of the storeImageDetails property.
     * 
     * @return
     *     possible object is
     *     {@link StreamImageDetailsJAXB }
     *     
     */
    public StreamImageDetailsJAXB getStoreImageDetails() {
        return storeImageDetails;
    }

    /**
     * Sets the value of the storeImageDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamImageDetailsJAXB }
     *     
     */
    public void setStoreImageDetails(StreamImageDetailsJAXB value) {
        this.storeImageDetails = value;
    }

    public Boolean isSetStoreImageDetails() {
        return (this.storeImageDetails!= null);
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateDate(Date value) {
        this.createDate = value;
    }

    public Boolean isSetCreateDate() {
        return (this.createDate!= null);
    }

    /**
     * Gets the value of the imageDetails property.
     * 
     * @return
     *     possible object is
     *     {@link StreamImageDetailsJAXB }
     *     
     */
    public StreamImageDetailsJAXB getImageDetails() {
        return imageDetails;
    }

    /**
     * Sets the value of the imageDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamImageDetailsJAXB }
     *     
     */
    public void setImageDetails(StreamImageDetailsJAXB value) {
        this.imageDetails = value;
    }

    public Boolean isSetImageDetails() {
        return (this.imageDetails!= null);
    }

    /**
     * Gets the value of the userAdded property.
     * 
     */
    public Boolean isUserAdded() {
        return userAdded;
    }

    /**
     * Sets the value of the userAdded property.
     * 
     */
    public void setUserAdded(Boolean value) {
        this.userAdded = value;
    }

    public Boolean isSetUserAdded() {
        return true;
    }

    /**
     * Gets the value of the sourceUser property.
     * 
     * @return
     *     possible object is
     *     {@link StreamUserDetailJAXB }
     *     
     */
    public StreamUserDetailJAXB getSourceUser() {
        return sourceUser;
    }

    /**
     * Sets the value of the sourceUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamUserDetailJAXB }
     *     
     */
    public void setSourceUser(StreamUserDetailJAXB value) {
        this.sourceUser = value;
    }

    public Boolean isSetSourceUser() {
        return (this.sourceUser!= null);
    }

    /**
     * Gets the value of the ownerUser property.
     * 
     * @return
     *     possible object is
     *     {@link StreamUserDetailJAXB }
     *     
     */
    public StreamUserDetailJAXB getOwnerUser() {
        return ownerUser;
    }

    /**
     * Sets the value of the ownerUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamUserDetailJAXB }
     *     
     */
    public void setOwnerUser(StreamUserDetailJAXB value) {
        this.ownerUser = value;
    }

    public Boolean isSetOwnerUser() {
        return (this.ownerUser!= null);
    }

    /**
     * Gets the value of the likes property.
     * 
     */
    public Long getLikes() {
        return likes;
    }

    /**
     * Sets the value of the likes property.
     * 
     */
    public void setLikes(Long value) {
        this.likes = value;
    }

    public Boolean isSetLikes() {
        return true;
    }

    /**
     * Gets the value of the comments property.
     * 
     */
    public Long getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     */
    public void setComments(Long value) {
        this.comments = value;
    }

    public Boolean isSetComments() {
        return true;
    }

    /**
     * Gets the value of the reviews property.
     * 
     */
    public Long getReviews() {
        return reviews;
    }

    /**
     * Sets the value of the reviews property.
     * 
     */
    public void setReviews(Long value) {
        this.reviews = value;
    }

    public Boolean isSetReviews() {
        return true;
    }

    /**
     * Gets the value of the tags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StreamTagsDetailJAXB }
     * 
     * 
     */
    public List<StreamTagsDetailJAXB> getTags() {
        if (tags == null) {
            tags = new ArrayList<StreamTagsDetailJAXB>();
        }
        return this.tags;
    }

    public Boolean isSetTags() {
        return ((this.tags!= null)&&(!this.tags.isEmpty()));
    }

    public void unsetTags() {
        this.tags = null;
    }

    /**
     * Gets the value of the branches property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the branches property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBranches().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StreamProducerBranchDetailJAXB }
     * 
     * 
     */
    public List<StreamProducerBranchDetailJAXB> getBranches() {
        if (branches == null) {
            branches = new ArrayList<StreamProducerBranchDetailJAXB>();
        }
        return this.branches;
    }

    public Boolean isSetBranches() {
        return ((this.branches!= null)&&(!this.branches.isEmpty()));
    }

    public void unsetBranches() {
        this.branches = null;
    }

    /**
     * Gets the value of the categories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StreamTagsDetailJAXB }
     * 
     * 
     */
    public List<StreamTagsDetailJAXB> getCategories() {
        if (categories == null) {
            categories = new ArrayList<StreamTagsDetailJAXB>();
        }
        return this.categories;
    }

    public Boolean isSetCategories() {
        return ((this.categories!= null)&&(!this.categories.isEmpty()));
    }

    public void unsetCategories() {
        this.categories = null;
    }

}
