//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.11 at 01:55:25 PM IST 
//


package com.ubiquity.common.jaxb.stream;

import java.io.Serializable;
import java.util.Date;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for StreamImageDetailsJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StreamImageDetailsJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imageBlobId" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="cdnKeyOriginal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cdnKeyTiny" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cdnKeyThumb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cdnKeySquare" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cdnKeyWeb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cdnKeyBig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cdnKeyWebList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="imageMimeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StreamImageDetailsJAXB", propOrder = {
    "imageBlobId",
    "cdnKeyOriginal",
    "cdnKeyTiny",
    "cdnKeyThumb",
    "cdnKeySquare",
    "cdnKeyWeb",
    "cdnKeyBig",
    "cdnKeyWebList",
    "createDate",
    "imageMimeType"
})
@XmlRootElement public class StreamImageDetailsJAXB
    implements Serializable
{

    private final static Long serialVersionUID = 12343L;
    protected Long imageBlobId;
    @XmlElement(required = true)
    protected String cdnKeyOriginal;
    @XmlElement(required = true)
    protected String cdnKeyTiny;
    @XmlElement(required = true)
    protected String cdnKeyThumb;
    @XmlElement(required = true)
    protected String cdnKeySquare;
    @XmlElement(required = true)
    protected String cdnKeyWeb;
    @XmlElement(required = true)
    protected String cdnKeyBig;
    @XmlElement(required = true)
    protected String cdnKeyWebList;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date createDate;
    @XmlElement(required = true)
    protected String imageMimeType;

    /**
     * Gets the value of the imageBlobId property.
     * 
     */
    public Long getImageBlobId() {
        return imageBlobId;
    }

    /**
     * Sets the value of the imageBlobId property.
     * 
     */
    public void setImageBlobId(Long value) {
        this.imageBlobId = value;
    }

    public Boolean isSetImageBlobId() {
        return true;
    }

    /**
     * Gets the value of the cdnKeyOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdnKeyOriginal() {
        return cdnKeyOriginal;
    }

    /**
     * Sets the value of the cdnKeyOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdnKeyOriginal(String value) {
        this.cdnKeyOriginal = value;
    }

    public Boolean isSetCdnKeyOriginal() {
        return (this.cdnKeyOriginal!= null);
    }

    /**
     * Gets the value of the cdnKeyTiny property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdnKeyTiny() {
        return cdnKeyTiny;
    }

    /**
     * Sets the value of the cdnKeyTiny property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdnKeyTiny(String value) {
        this.cdnKeyTiny = value;
    }

    public Boolean isSetCdnKeyTiny() {
        return (this.cdnKeyTiny!= null);
    }

    /**
     * Gets the value of the cdnKeyThumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdnKeyThumb() {
        return cdnKeyThumb;
    }

    /**
     * Sets the value of the cdnKeyThumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdnKeyThumb(String value) {
        this.cdnKeyThumb = value;
    }

    public Boolean isSetCdnKeyThumb() {
        return (this.cdnKeyThumb!= null);
    }

    /**
     * Gets the value of the cdnKeySquare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdnKeySquare() {
        return cdnKeySquare;
    }

    /**
     * Sets the value of the cdnKeySquare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdnKeySquare(String value) {
        this.cdnKeySquare = value;
    }

    public Boolean isSetCdnKeySquare() {
        return (this.cdnKeySquare!= null);
    }

    /**
     * Gets the value of the cdnKeyWeb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdnKeyWeb() {
        return cdnKeyWeb;
    }

    /**
     * Sets the value of the cdnKeyWeb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdnKeyWeb(String value) {
        this.cdnKeyWeb = value;
    }

    public Boolean isSetCdnKeyWeb() {
        return (this.cdnKeyWeb!= null);
    }

    /**
     * Gets the value of the cdnKeyBig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdnKeyBig() {
        return cdnKeyBig;
    }

    /**
     * Sets the value of the cdnKeyBig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdnKeyBig(String value) {
        this.cdnKeyBig = value;
    }

    public Boolean isSetCdnKeyBig() {
        return (this.cdnKeyBig!= null);
    }

    /**
     * Gets the value of the cdnKeyWebList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdnKeyWebList() {
        return cdnKeyWebList;
    }

    /**
     * Sets the value of the cdnKeyWebList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdnKeyWebList(String value) {
        this.cdnKeyWebList = value;
    }

    public Boolean isSetCdnKeyWebList() {
        return (this.cdnKeyWebList!= null);
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateDate(Date value) {
        this.createDate = value;
    }

    public Boolean isSetCreateDate() {
        return (this.createDate!= null);
    }

    /**
     * Gets the value of the imageMimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageMimeType() {
        return imageMimeType;
    }

    /**
     * Sets the value of the imageMimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageMimeType(String value) {
        this.imageMimeType = value;
    }

    public Boolean isSetImageMimeType() {
        return (this.imageMimeType!= null);
    }

}
