//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.11 at 01:55:25 PM IST 
//


package com.ubiquity.common.jaxb.stream;

import java.io.Serializable;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StreamRewardDetailJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StreamRewardDetailJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rewardId" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="rewardTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rewardPoint" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StreamRewardDetailJAXB", propOrder = {
    "rewardId",
    "rewardTitle",
    "rewardPoint"
})
@XmlRootElement public class StreamRewardDetailJAXB
    implements Serializable
{

    private final static Long serialVersionUID = 12343L;
    protected Long rewardId;
    @XmlElement(required = true)
    protected String rewardTitle;
    protected Long rewardPoint;

    /**
     * Gets the value of the rewardId property.
     * 
     */
    public Long getRewardId() {
        return rewardId;
    }

    /**
     * Sets the value of the rewardId property.
     * 
     */
    public void setRewardId(Long value) {
        this.rewardId = value;
    }

    public Boolean isSetRewardId() {
        return true;
    }

    /**
     * Gets the value of the rewardTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRewardTitle() {
        return rewardTitle;
    }

    /**
     * Sets the value of the rewardTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRewardTitle(String value) {
        this.rewardTitle = value;
    }

    public Boolean isSetRewardTitle() {
        return (this.rewardTitle!= null);
    }

    /**
     * Gets the value of the rewardPoint property.
     * 
     */
    public Long getRewardPoint() {
        return rewardPoint;
    }

    /**
     * Sets the value of the rewardPoint property.
     * 
     */
    public void setRewardPoint(Long value) {
        this.rewardPoint = value;
    }

    public Boolean isSetRewardPoint() {
        return true;
    }

}
