//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 01:09:10 PM IST 
//


package com.ubiquity.common.jaxb.themecollection;

import com.ubiquity.common.jaxb.ecomm.EcommProductLimitedJAXB;
import com.ubiquity.common.jaxb.stream.FashionLookLimitedJAXB;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CollectionJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CollectionJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="object_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CollectionJAXB", propOrder = {
    "objectType",
    "objectId",
        "productJAXB",
        "lookJAXB"
})
public class CollectionJAXB {

    @XmlElement(name = "object_type", required = true)
    protected String objectType;
    @XmlElement(name = "object_id")
    protected long objectId;

    protected EcommProductLimitedJAXB productJAXB;

    protected FashionLookLimitedJAXB lookJAXB;

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectType(String value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the objectId property.
     * 
     */
    public long getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     */
    public void setObjectId(long value) {
        this.objectId = value;
    }

    public FashionLookLimitedJAXB getLookJAXB() {
        return lookJAXB;
    }

    public void setLookJAXB(FashionLookLimitedJAXB lookJAXB) {
        this.lookJAXB = lookJAXB;
    }

    public EcommProductLimitedJAXB getProductJAXB() {
        return productJAXB;
    }

    public void setProductJAXB(EcommProductLimitedJAXB productJAXB) {
        this.productJAXB = productJAXB;
    }
}
