//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.06 at 02:06:28 PM IST 
//


package com.ubiquity.common.jaxb.suggestion;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ubiquity.common.jaxb.suggestion package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SuggestionForm_QNAME = new QName("", "suggestionForm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ubiquity.common.jaxb.suggestion
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SuggestionJAXB }
     * 
     */
    public SuggestionJAXB createSuggestionJAXB() {
        return new SuggestionJAXB();
    }

    /**
     * Create an instance of {@link SuggestedPersonJAXB }
     * 
     */
    public SuggestedPersonJAXB createSuggestedPersonJAXB() {
        return new SuggestedPersonJAXB();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SuggestionJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "suggestionForm")
    public JAXBElement<SuggestionJAXB> createSuggestionForm(SuggestionJAXB value) {
        return new JAXBElement<SuggestionJAXB>(_SuggestionForm_QNAME, SuggestionJAXB.class, null, value);
    }

}
