//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.19 at 10:29:04 PM IST 
//


package com.ubiquity.common.jaxb.producerProduct;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ubiquity.common.jaxb.producerProduct package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProducerProductForm_QNAME = new QName("", "producerProductForm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ubiquity.common.jaxb.producerProduct
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProductActivityDetailsJAXB }
     * 
     */
    public ProductActivityDetailsJAXB createProductActivityDetailsJAXB() {
        return new ProductActivityDetailsJAXB();
    }

    /**
     * Create an instance of {@link ProducerProductDetailsJAXB }
     * 
     */
    public ProducerProductDetailsJAXB createProducerProductDetailsJAXB() {
        return new ProducerProductDetailsJAXB();
    }

    /**
     * Create an instance of {@link ProducerProductTagsJAXB }
     * 
     */
    public ProducerProductTagsJAXB createProducerProductTagsJAXB() {
        return new ProducerProductTagsJAXB();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProducerProductDetailsJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "producerProductForm")
    public JAXBElement<ProducerProductDetailsJAXB> createProducerProductForm(ProducerProductDetailsJAXB value) {
        return new JAXBElement<ProducerProductDetailsJAXB>(_ProducerProductForm_QNAME, ProducerProductDetailsJAXB.class, null, value);
    }

}
