//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 03:43:40 AM IST 
//


package com.ubiquity.common.jaxb.urlView;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ubiquity.common.jaxb.urlView package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UrlViewDetailForm_QNAME = new QName("", "urlViewDetailForm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ubiquity.common.jaxb.urlView
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UrlViewDetailJAXB }
     * 
     */
    public UrlViewDetailJAXB createUrlViewDetailJAXB() {
        return new UrlViewDetailJAXB();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UrlViewDetailJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "urlViewDetailForm")
    public JAXBElement<UrlViewDetailJAXB> createUrlViewDetailForm(UrlViewDetailJAXB value) {
        return new JAXBElement<UrlViewDetailJAXB>(_UrlViewDetailForm_QNAME, UrlViewDetailJAXB.class, null, value);
    }

}
