//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.19 at 06:18:04 PM IST 
//


package com.ubiquity.common.jaxb.userrecommendation;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userRecommendationEntityListJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userRecommendationEntityListJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="recommendationCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="streamEntries" type="{}userRecommendationEntityJAXB" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userRecommendationEntityListJAXB", propOrder = {
    "userId",
    "recommendationCount",
    "streamEntries"
})
public class UserRecommendationEntityListJAXB
    implements Serializable
{

    private final static long serialVersionUID = 2081985L;
    protected Long userId;
    protected Long recommendationCount;
    @XmlElement(nillable = true)
    protected List<UserRecommendationEntityJAXB> streamEntries;

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUserId(Long value) {
        this.userId = value;
    }

    public boolean isSetUserId() {
        return (this.userId!= null);
    }

    /**
     * Gets the value of the recommendationCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRecommendationCount() {
        return recommendationCount;
    }

    /**
     * Sets the value of the recommendationCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRecommendationCount(Long value) {
        this.recommendationCount = value;
    }

    public boolean isSetRecommendationCount() {
        return (this.recommendationCount!= null);
    }

    /**
     * Gets the value of the streamEntries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the streamEntries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStreamEntries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserRecommendationEntityJAXB }
     * 
     * 
     */
    public List<UserRecommendationEntityJAXB> getStreamEntries() {
        if (streamEntries == null) {
            streamEntries = new ArrayList<UserRecommendationEntityJAXB>();
        }
        return this.streamEntries;
    }

    public boolean isSetStreamEntries() {
        return ((this.streamEntries!= null)&&(!this.streamEntries.isEmpty()));
    }

    public void unsetStreamEntries() {
        this.streamEntries = null;
    }

}
