//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.13 at 05:19:39 PM IST 
//


package com.ubiquity.common.jaxb.entityFull;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for dealDetailFullJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dealDetailFullJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adminCreated" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="productDeal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="imageMimeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="producerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="serviceId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="producerCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="producerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="terms" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="highlights" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="liked" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="dealView" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="likes" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="reviews" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="tags" type="{}EntityTagsDetailFullJAXB" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="address" type="{}ProducerAddressDetailJAXB"/>
 *         &lt;element name="dealAddr" type="{}ProducerAddressDetailJAXB" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="categoryTag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="availablenum" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="privateDeal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="privateDealCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dealDetailFullJAXB", propOrder = {
    "adminCreated",
    "productDeal",
    "image",
    "imageMimeType",
    "description",
    "endDate",
    "id",
    "producerId",
    "productId",
    "serviceId",
    "startDate",
    "title",
    "producerCode",
    "producerName",
    "productName",
    "terms",
    "highlights",
    "liked",
    "dealView",
    "likes",
    "comments",
    "reviews",
    "tags",
    "address",
    "dealAddr",
    "categoryTag",
    "website",
    "availablenum",
    "privateDeal",
    "privateDealCode"
})
public class DealDetailFullJAXB
    implements Serializable
{

    private final static long serialVersionUID = 123434L;
    protected boolean adminCreated;
    protected boolean productDeal;
    @XmlElement(required = true)
    protected byte[] image;
    @XmlElement(required = true)
    protected String imageMimeType;
    protected String description;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    protected long id;
    protected long producerId;
    protected long productId;
    protected long serviceId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    protected String title;
    protected String producerCode;
    protected String producerName;
    protected String productName;
    protected String terms;
    protected String highlights;
    protected boolean liked;
    protected long dealView;
    protected long likes;
    protected long comments;
    protected long reviews;
    @XmlElement(nillable = true)
    protected List<EntityTagsDetailFullJAXB> tags;
    @XmlElement(required = true)
    protected ProducerAddressDetailJAXB address;
    @XmlElement(nillable = true)
    protected List<ProducerAddressDetailJAXB> dealAddr;
    protected String categoryTag;
    protected String website;
    protected Long availablenum;
    protected boolean privateDeal;
    protected String privateDealCode;

    /**
     * Gets the value of the adminCreated property.
     * 
     */
    public boolean isAdminCreated() {
        return adminCreated;
    }

    /**
     * Sets the value of the adminCreated property.
     * 
     */
    public void setAdminCreated(boolean value) {
        this.adminCreated = value;
    }

    public boolean isSetAdminCreated() {
        return true;
    }

    /**
     * Gets the value of the productDeal property.
     * 
     */
    public boolean isProductDeal() {
        return productDeal;
    }

    /**
     * Sets the value of the productDeal property.
     * 
     */
    public void setProductDeal(boolean value) {
        this.productDeal = value;
    }

    public boolean isSetProductDeal() {
        return true;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setImage(byte[] value) {
        this.image = ((byte[]) value);
    }

    public boolean isSetImage() {
        return (this.image!= null);
    }

    /**
     * Gets the value of the imageMimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageMimeType() {
        return imageMimeType;
    }

    /**
     * Sets the value of the imageMimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageMimeType(String value) {
        this.imageMimeType = value;
    }

    public boolean isSetImageMimeType() {
        return (this.imageMimeType!= null);
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    public boolean isSetDescription() {
        return (this.description!= null);
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    public boolean isSetEndDate() {
        return (this.endDate!= null);
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    public boolean isSetId() {
        return true;
    }

    /**
     * Gets the value of the producerId property.
     * 
     */
    public long getProducerId() {
        return producerId;
    }

    /**
     * Sets the value of the producerId property.
     * 
     */
    public void setProducerId(long value) {
        this.producerId = value;
    }

    public boolean isSetProducerId() {
        return true;
    }

    /**
     * Gets the value of the productId property.
     * 
     */
    public long getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     */
    public void setProductId(long value) {
        this.productId = value;
    }

    public boolean isSetProductId() {
        return true;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     */
    public long getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     */
    public void setServiceId(long value) {
        this.serviceId = value;
    }

    public boolean isSetServiceId() {
        return true;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    public boolean isSetStartDate() {
        return (this.startDate!= null);
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    public boolean isSetTitle() {
        return (this.title!= null);
    }

    /**
     * Gets the value of the producerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerCode() {
        return producerCode;
    }

    /**
     * Sets the value of the producerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerCode(String value) {
        this.producerCode = value;
    }

    public boolean isSetProducerCode() {
        return (this.producerCode!= null);
    }

    /**
     * Gets the value of the producerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerName() {
        return producerName;
    }

    /**
     * Sets the value of the producerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerName(String value) {
        this.producerName = value;
    }

    public boolean isSetProducerName() {
        return (this.producerName!= null);
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    public boolean isSetProductName() {
        return (this.productName!= null);
    }

    /**
     * Gets the value of the terms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerms() {
        return terms;
    }

    /**
     * Sets the value of the terms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerms(String value) {
        this.terms = value;
    }

    public boolean isSetTerms() {
        return (this.terms!= null);
    }

    /**
     * Gets the value of the highlights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighlights() {
        return highlights;
    }

    /**
     * Sets the value of the highlights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighlights(String value) {
        this.highlights = value;
    }

    public boolean isSetHighlights() {
        return (this.highlights!= null);
    }

    /**
     * Gets the value of the liked property.
     * 
     */
    public boolean isLiked() {
        return liked;
    }

    /**
     * Sets the value of the liked property.
     * 
     */
    public void setLiked(boolean value) {
        this.liked = value;
    }

    public boolean isSetLiked() {
        return true;
    }

    /**
     * Gets the value of the dealView property.
     * 
     */
    public long getDealView() {
        return dealView;
    }

    /**
     * Sets the value of the dealView property.
     * 
     */
    public void setDealView(long value) {
        this.dealView = value;
    }

    public boolean isSetDealView() {
        return true;
    }

    /**
     * Gets the value of the likes property.
     * 
     */
    public long getLikes() {
        return likes;
    }

    /**
     * Sets the value of the likes property.
     * 
     */
    public void setLikes(long value) {
        this.likes = value;
    }

    public boolean isSetLikes() {
        return true;
    }

    /**
     * Gets the value of the comments property.
     * 
     */
    public long getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     */
    public void setComments(long value) {
        this.comments = value;
    }

    public boolean isSetComments() {
        return true;
    }

    /**
     * Gets the value of the reviews property.
     * 
     */
    public long getReviews() {
        return reviews;
    }

    /**
     * Sets the value of the reviews property.
     * 
     */
    public void setReviews(long value) {
        this.reviews = value;
    }

    public boolean isSetReviews() {
        return true;
    }

    /**
     * Gets the value of the tags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityTagsDetailFullJAXB }
     * 
     * 
     */
    public List<EntityTagsDetailFullJAXB> getTags() {
        if (tags == null) {
            tags = new ArrayList<EntityTagsDetailFullJAXB>();
        }
        return this.tags;
    }

    public boolean isSetTags() {
        return ((this.tags!= null)&&(!this.tags.isEmpty()));
    }

    public void unsetTags() {
        this.tags = null;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link ProducerAddressDetailJAXB }
     *     
     */
    public ProducerAddressDetailJAXB getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProducerAddressDetailJAXB }
     *     
     */
    public void setAddress(ProducerAddressDetailJAXB value) {
        this.address = value;
    }

    public boolean isSetAddress() {
        return (this.address!= null);
    }

    /**
     * Gets the value of the dealAddr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dealAddr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDealAddr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProducerAddressDetailJAXB }
     * 
     * 
     */
    public List<ProducerAddressDetailJAXB> getDealAddr() {
        if (dealAddr == null) {
            dealAddr = new ArrayList<ProducerAddressDetailJAXB>();
        }
        return this.dealAddr;
    }

    public boolean isSetDealAddr() {
        return ((this.dealAddr!= null)&&(!this.dealAddr.isEmpty()));
    }

    public void unsetDealAddr() {
        this.dealAddr = null;
    }

    /**
     * Gets the value of the categoryTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryTag() {
        return categoryTag;
    }

    /**
     * Sets the value of the categoryTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryTag(String value) {
        this.categoryTag = value;
    }

    public boolean isSetCategoryTag() {
        return (this.categoryTag!= null);
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    public boolean isSetWebsite() {
        return (this.website!= null);
    }

    /**
     * Gets the value of the availablenum property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAvailablenum() {
        return availablenum;
    }

    /**
     * Sets the value of the availablenum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAvailablenum(Long value) {
        this.availablenum = value;
    }

    public boolean isSetAvailablenum() {
        return (this.availablenum!= null);
    }

    /**
     * Gets the value of the privateDeal property.
     * 
     */
    public boolean isPrivateDeal() {
        return privateDeal;
    }

    /**
     * Sets the value of the privateDeal property.
     * 
     */
    public void setPrivateDeal(boolean value) {
        this.privateDeal = value;
    }

    public boolean isSetPrivateDeal() {
        return true;
    }

    /**
     * Gets the value of the privateDealCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateDealCode() {
        return privateDealCode;
    }

    /**
     * Sets the value of the privateDealCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateDealCode(String value) {
        this.privateDealCode = value;
    }

    public boolean isSetPrivateDealCode() {
        return (this.privateDealCode!= null);
    }

}
