//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.13 at 05:19:39 PM IST 
//


package com.ubiquity.common.jaxb.entityFull;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for reviewJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reviewJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="canShow" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bySMS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="createdDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="oldCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="orphan" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="approved" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="points" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tagsFull" type="{}EntityTagsDetailFullJAXB" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="address" type="{}ProducerAddressDetailJAXB"/>
 *         &lt;element name="sponsoredPointsId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="locations" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="orphanImageId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="imageMimeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reviewJAXB", propOrder = {
    "canShow",
    "bySMS",
    "mobile",
    "createdDate",
    "description",
    "category",
    "oldCategory",
    "title",
    "id",
    "location",
    "orphan",
    "rating",
    "approved",
    "userId",
    "userName",
    "points",
    "tags",
    "tagsFull",
    "address",
    "sponsoredPointsId",
    "locations",
    "image",
    "orphanImageId",
    "imageMimeType",
    "recommendedByProducer"
})
@XmlSeeAlso({
    ProducerServiceReviewDetailsJAXB.class,
    ProductReviewDetailsJAXB.class,
    DealReviewDetailsJAXB.class,
    ProducerReviewDetailsJAXB.class,
    ServiceReviewDetailsJAXB.class,
    ProducerProductReviewDetailsJAXB.class
})
public class ReviewJAXB
    implements Serializable
{

    private final static long serialVersionUID = 123434L;
    protected boolean canShow;
    protected boolean bySMS;
    protected boolean mobile;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDate;
    protected String description;
    protected String category;
    protected String oldCategory;
    protected String title;
    protected Long id;
    protected long location;
    protected boolean orphan;
    protected double rating;
    protected boolean approved;
    protected long userId;
    @XmlElement(required = true)
    protected String userName;
    protected int points;
    protected String tags;
    @XmlElement(nillable = true)
    protected List<EntityTagsDetailFullJAXB> tagsFull;
    @XmlElement(required = true)
    protected ProducerAddressDetailJAXB address;
    protected Long sponsoredPointsId;
    @XmlElement(nillable = true)
    protected List<Long> locations;
    @XmlElement(required = true)
    protected byte[] image;
    protected long orphanImageId;
    @XmlElement(required = true)
    protected String imageMimeType;
    protected boolean recommendedByProducer;
    /**
     * Gets the value of the canShow property.
     * 
     */
    public boolean isCanShow() {
        return canShow;
    }

    /**
     * Sets the value of the canShow property.
     * 
     */
    public void setCanShow(boolean value) {
        this.canShow = value;
    }

    public boolean isSetCanShow() {
        return true;
    }

    /**
     * Gets the value of the bySMS property.
     * 
     */
    public boolean isBySMS() {
        return bySMS;
    }

    /**
     * Sets the value of the bySMS property.
     * 
     */
    public void setBySMS(boolean value) {
        this.bySMS = value;
    }

    public boolean isSetBySMS() {
        return true;
    }

    /**
     * Gets the value of the mobile property.
     * 
     */
    public boolean isMobile() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     */
    public void setMobile(boolean value) {
        this.mobile = value;
    }

    public boolean isSetMobile() {
        return true;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    public boolean isSetCreatedDate() {
        return (this.createdDate!= null);
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    public boolean isSetDescription() {
        return (this.description!= null);
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    public boolean isSetCategory() {
        return (this.category!= null);
    }

    /**
     * Gets the value of the oldCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldCategory() {
        return oldCategory;
    }

    /**
     * Sets the value of the oldCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldCategory(String value) {
        this.oldCategory = value;
    }

    public boolean isSetOldCategory() {
        return (this.oldCategory!= null);
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    public boolean isSetTitle() {
        return (this.title!= null);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id!= null);
    }

    /**
     * Gets the value of the location property.
     * 
     */
    public long getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     */
    public void setLocation(long value) {
        this.location = value;
    }

    public boolean isSetLocation() {
        return true;
    }

    /**
     * Gets the value of the orphan property.
     * 
     */
    public boolean isOrphan() {
        return orphan;
    }

    /**
     * Sets the value of the orphan property.
     * 
     */
    public void setOrphan(boolean value) {
        this.orphan = value;
    }

    public boolean isSetOrphan() {
        return true;
    }

    /**
     * Gets the value of the rating property.
     * 
     */
    public double getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     */
    public void setRating(double value) {
        this.rating = value;
    }

    public boolean isSetRating() {
        return true;
    }

    /**
     * Gets the value of the approved property.
     * 
     */
    public boolean isApproved() {
        return approved;
    }

    /**
     * Sets the value of the approved property.
     * 
     */
    public void setApproved(boolean value) {
        this.approved = value;
    }

    public boolean isSetApproved() {
        return true;
    }

    /**
     * Gets the value of the userId property.
     * 
     */
    public long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(long value) {
        this.userId = value;
    }

    public boolean isSetUserId() {
        return true;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    public boolean isSetUserName() {
        return (this.userName!= null);
    }

    /**
     * Gets the value of the points property.
     * 
     */
    public int getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     * 
     */
    public void setPoints(int value) {
        this.points = value;
    }

    public boolean isSetPoints() {
        return true;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTags(String value) {
        this.tags = value;
    }

    public boolean isSetTags() {
        return (this.tags!= null);
    }

    /**
     * Gets the value of the tagsFull property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tagsFull property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTagsFull().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityTagsDetailFullJAXB }
     * 
     * 
     */
    public List<EntityTagsDetailFullJAXB> getTagsFull() {
        if (tagsFull == null) {
            tagsFull = new ArrayList<EntityTagsDetailFullJAXB>();
        }
        return this.tagsFull;
    }

    public boolean isSetTagsFull() {
        return ((this.tagsFull!= null)&&(!this.tagsFull.isEmpty()));
    }

    public void unsetTagsFull() {
        this.tagsFull = null;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link ProducerAddressDetailJAXB }
     *     
     */
    public ProducerAddressDetailJAXB getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProducerAddressDetailJAXB }
     *     
     */
    public void setAddress(ProducerAddressDetailJAXB value) {
        this.address = value;
    }

    public boolean isSetAddress() {
        return (this.address!= null);
    }

    /**
     * Gets the value of the sponsoredPointsId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSponsoredPointsId() {
        return sponsoredPointsId;
    }

    /**
     * Sets the value of the sponsoredPointsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSponsoredPointsId(Long value) {
        this.sponsoredPointsId = value;
    }

    public boolean isSetSponsoredPointsId() {
        return (this.sponsoredPointsId!= null);
    }

    /**
     * Gets the value of the locations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getLocations() {
        if (locations == null) {
            locations = new ArrayList<Long>();
        }
        return this.locations;
    }

    public boolean isSetLocations() {
        return ((this.locations!= null)&&(!this.locations.isEmpty()));
    }

    public void unsetLocations() {
        this.locations = null;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setImage(byte[] value) {
        this.image = ((byte[]) value);
    }

    public boolean isSetImage() {
        return (this.image!= null);
    }

    /**
     * Gets the value of the orphanImageId property.
     * 
     */
    public long getOrphanImageId() {
        return orphanImageId;
    }

    /**
     * Sets the value of the orphanImageId property.
     * 
     */
    public void setOrphanImageId(long value) {
        this.orphanImageId = value;
    }

    public boolean isSetOrphanImageId() {
        return true;
    }

    /**
     * Gets the value of the imageMimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageMimeType() {
        return imageMimeType;
    }

    /**
     * Sets the value of the imageMimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageMimeType(String value) {
        this.imageMimeType = value;
    }

    public boolean isSetImageMimeType() {
        return (this.imageMimeType!= null);
    }

    public boolean isRecommendedByProducer() {
        return recommendedByProducer;
    }

    public void setRecommendedByProducer(boolean recommendedByProducer) {
        this.recommendedByProducer = recommendedByProducer;
    }
}
