//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.13 at 05:19:39 PM IST 
//


package com.ubiquity.common.jaxb.entityFull;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;


/**
 * <p>Java class for UserEmailNotificationSettingsJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserEmailNotificationSettingsJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="likeNotification" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="shareNotification" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="commentNotification" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="followNotification" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="weeklyNotification" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="secondLevelNotification" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserEmailNotificationSettingsJAXB", propOrder = {
    "userId",
    "likeNotification",
    "shareNotification",
    "commentNotification",
    "followNotification",
    "weeklyNotification",
    "secondLevelNotification",
    "createDate"
})
public class UserEmailNotificationSettingsJAXB
    implements Serializable
{

    private final static long serialVersionUID = 123434L;
    protected long userId;
    protected boolean likeNotification;
    protected boolean shareNotification;
    protected boolean commentNotification;
    protected boolean followNotification;
    protected boolean weeklyNotification;
    protected boolean secondLevelNotification;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createDate;

    /**
     * Gets the value of the userId property.
     * 
     */
    public long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(long value) {
        this.userId = value;
    }

    public boolean isSetUserId() {
        return true;
    }

    /**
     * Gets the value of the likeNotification property.
     * 
     */
    public boolean isLikeNotification() {
        return likeNotification;
    }

    /**
     * Sets the value of the likeNotification property.
     * 
     */
    public void setLikeNotification(boolean value) {
        this.likeNotification = value;
    }

    public boolean isSetLikeNotification() {
        return true;
    }

    /**
     * Gets the value of the shareNotification property.
     * 
     */
    public boolean isShareNotification() {
        return shareNotification;
    }

    /**
     * Sets the value of the shareNotification property.
     * 
     */
    public void setShareNotification(boolean value) {
        this.shareNotification = value;
    }

    public boolean isSetShareNotification() {
        return true;
    }

    /**
     * Gets the value of the commentNotification property.
     * 
     */
    public boolean isCommentNotification() {
        return commentNotification;
    }

    /**
     * Sets the value of the commentNotification property.
     * 
     */
    public void setCommentNotification(boolean value) {
        this.commentNotification = value;
    }

    public boolean isSetCommentNotification() {
        return true;
    }

    /**
     * Gets the value of the followNotification property.
     * 
     */
    public boolean isFollowNotification() {
        return followNotification;
    }

    /**
     * Sets the value of the followNotification property.
     * 
     */
    public void setFollowNotification(boolean value) {
        this.followNotification = value;
    }

    public boolean isSetFollowNotification() {
        return true;
    }

    /**
     * Gets the value of the weeklyNotification property.
     * 
     */
    public boolean isWeeklyNotification() {
        return weeklyNotification;
    }

    /**
     * Sets the value of the weeklyNotification property.
     * 
     */
    public void setWeeklyNotification(boolean value) {
        this.weeklyNotification = value;
    }

    public boolean isSetWeeklyNotification() {
        return true;
    }

    /**
     * Gets the value of the secondLevelNotification property.
     * 
     */
    public boolean isSecondLevelNotification() {
        return secondLevelNotification;
    }

    /**
     * Sets the value of the secondLevelNotification property.
     * 
     */
    public void setSecondLevelNotification(boolean value) {
        this.secondLevelNotification = value;
    }

    public boolean isSetSecondLevelNotification() {
        return true;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDate(XMLGregorianCalendar value) {
        this.createDate = value;
    }

    public boolean isSetCreateDate() {
        return (this.createDate!= null);
    }

}
