//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.13 at 05:19:39 PM IST 
//


package com.ubiquity.common.jaxb.entityFull;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserDetailSmallJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserDetailSmallJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userFollow" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userRecommendations" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userLovesReceived" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="facebook" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="twitter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="blog" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserDetailSmallJAXB", propOrder = {
    "userId",
    "userName",
    "userRole",
    "userFollow",
    "userRecommendations",
    "userLovesReceived",
    "location",
    "facebook",
    "twitter",
    "blog"
})
public class UserDetailSmallJAXB
    implements Serializable
{

    private final static long serialVersionUID = 123434L;
    protected long userId;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected String userRole;
    protected long userFollow;
    protected long userRecommendations;
    protected long userLovesReceived;
    @XmlElement(required = true)
    protected String location;
    @XmlElement(required = true)
    protected String facebook;
    @XmlElement(required = true)
    protected String twitter;
    @XmlElement(required = true)
    protected String blog;

    /**
     * Gets the value of the userId property.
     * 
     */
    public long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(long value) {
        this.userId = value;
    }

    public boolean isSetUserId() {
        return true;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    public boolean isSetUserName() {
        return (this.userName!= null);
    }

    /**
     * Gets the value of the userRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * Sets the value of the userRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRole(String value) {
        this.userRole = value;
    }

    public boolean isSetUserRole() {
        return (this.userRole!= null);
    }

    /**
     * Gets the value of the userFollow property.
     * 
     */
    public long getUserFollow() {
        return userFollow;
    }

    /**
     * Sets the value of the userFollow property.
     * 
     */
    public void setUserFollow(long value) {
        this.userFollow = value;
    }

    public boolean isSetUserFollow() {
        return true;
    }

    /**
     * Gets the value of the userRecommendations property.
     * 
     */
    public long getUserRecommendations() {
        return userRecommendations;
    }

    /**
     * Sets the value of the userRecommendations property.
     * 
     */
    public void setUserRecommendations(long value) {
        this.userRecommendations = value;
    }

    public boolean isSetUserRecommendations() {
        return true;
    }

    /**
     * Gets the value of the userLovesReceived property.
     * 
     */
    public long getUserLovesReceived() {
        return userLovesReceived;
    }

    /**
     * Sets the value of the userLovesReceived property.
     * 
     */
    public void setUserLovesReceived(long value) {
        this.userLovesReceived = value;
    }

    public boolean isSetUserLovesReceived() {
        return true;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    public boolean isSetLocation() {
        return (this.location!= null);
    }

    /**
     * Gets the value of the facebook property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacebook() {
        return facebook;
    }

    /**
     * Sets the value of the facebook property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacebook(String value) {
        this.facebook = value;
    }

    public boolean isSetFacebook() {
        return (this.facebook!= null);
    }

    /**
     * Gets the value of the twitter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTwitter() {
        return twitter;
    }

    /**
     * Sets the value of the twitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTwitter(String value) {
        this.twitter = value;
    }

    public boolean isSetTwitter() {
        return (this.twitter!= null);
    }

    /**
     * Gets the value of the blog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlog() {
        return blog;
    }

    /**
     * Sets the value of the blog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlog(String value) {
        this.blog = value;
    }

    public boolean isSetBlog() {
        return (this.blog!= null);
    }

}
