//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.13 at 11:35:37 PM IST 
//


package com.ubiquity.common.jaxb.userrewards;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userRewardBadgesJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userRewardBadgesJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="badgeId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="badgeImageId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="earned" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userRewardBadgesJAXB", propOrder = {
    "badgeId",
    "badgeImageId",
    "earned",
    "desc"
})
public class UserRewardBadgesJAXB {

    protected long badgeId;
    protected long badgeImageId;
    protected boolean earned;
    @XmlElement(required = true)
    protected String desc;

    /**
     * Gets the value of the badgeId property.
     * 
     */
    public long getBadgeId() {
        return badgeId;
    }

    /**
     * Sets the value of the badgeId property.
     * 
     */
    public void setBadgeId(long value) {
        this.badgeId = value;
    }

    /**
     * Gets the value of the badgeImageId property.
     * 
     */
    public long getBadgeImageId() {
        return badgeImageId;
    }

    /**
     * Sets the value of the badgeImageId property.
     * 
     */
    public void setBadgeImageId(long value) {
        this.badgeImageId = value;
    }

    /**
     * Gets the value of the earned property.
     * 
     */
    public boolean isEarned() {
        return earned;
    }

    /**
     * Sets the value of the earned property.
     * 
     */
    public void setEarned(boolean value) {
        this.earned = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

}
