//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.29 at 10:54:32 AM IST 
//


package com.ubiquity.common.jaxb.admin.stream;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AdminStreamEntryRepresentationJAXB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdminStreamEntryRepresentationJAXB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="entrytype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="dealDetails" type="{}AdminDealStreamEntryRepresentationJAXB"/>
 *         &lt;element name="permissionDetails" type="{}AdminPermissionStreamEntryRepresentationJAXB"/>
 *         &lt;element name="userPermissionDetails" type="{}AdminUserPermStreamEntryRepresentationJAXB"/>
 *         &lt;element name="producerProductDetails" type="{}AdminProducerProductEntryRepresentationJAXB"/>
 *         &lt;element name="sponsoredPointDetails" type="{}AdminSponsoredPointsStreamEntryRepresentationJAXB"/>
 *         &lt;element name="sponsoredRewardDetails" type="{}AdminSponsoredRewardStreamEntryRepresentationJAXB"/>
 *         &lt;element name="sponsoredRequestDetails" type="{}AdminSponsoredRequestStreamEntryRepresentationJAXB"/>
 *         &lt;element name="producerReviewDetails" type="{}AdminProducerReviewStreamEntryRepresentationJAXB"/>
 *         &lt;element name="productReviewDetails" type="{}AdminProductReviewStreamEntryRepresentationJAXB"/>
 *         &lt;element name="dealReviewDetails" type="{}AdminDealReviewStreamEntryRepresentationJAXB"/>
 *         &lt;element name="badgeDetails" type="{}AdminBadgeStreamEntryRepresentationJAXB"/>
 *         &lt;element name="landingPageSuggestionDetails" type="{}AdminLandingPageSuggestionStreamEntryRepresentationJAXB"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdminStreamEntryRepresentationJAXB", propOrder = {
    "id",
    "entrytype",
    "weight",
    "timestamp",
    "dealDetails",
    "permissionDetails",
    "userPermissionDetails",
    "producerProductDetails",
    "sponsoredPointDetails",
    "sponsoredRewardDetails",
    "sponsoredRequestDetails",
    "producerReviewDetails",
    "productReviewDetails",
    "dealReviewDetails",
    "badgeDetails",
    "landingPageSuggestionDetails"
})
public class AdminStreamEntryRepresentationJAXB {

    protected long id;
    @XmlElement(required = true)
    protected String entrytype;
    protected long weight;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(required = true)
    protected AdminDealStreamEntryRepresentationJAXB dealDetails;
    @XmlElement(required = true)
    protected AdminPermissionStreamEntryRepresentationJAXB permissionDetails;
    @XmlElement(required = true)
    protected AdminUserPermStreamEntryRepresentationJAXB userPermissionDetails;
    @XmlElement(required = true)
    protected AdminProducerProductEntryRepresentationJAXB producerProductDetails;
    @XmlElement(required = true)
    protected AdminSponsoredPointsStreamEntryRepresentationJAXB sponsoredPointDetails;
    @XmlElement(required = true)
    protected AdminSponsoredRewardStreamEntryRepresentationJAXB sponsoredRewardDetails;
    @XmlElement(required = true)
    protected AdminSponsoredRequestStreamEntryRepresentationJAXB sponsoredRequestDetails;
    @XmlElement(required = true)
    protected AdminProducerReviewStreamEntryRepresentationJAXB producerReviewDetails;
    @XmlElement(required = true)
    protected AdminProductReviewStreamEntryRepresentationJAXB productReviewDetails;
    @XmlElement(required = true)
    protected AdminDealReviewStreamEntryRepresentationJAXB dealReviewDetails;
    @XmlElement(required = true)
    protected AdminBadgeStreamEntryRepresentationJAXB badgeDetails;
    @XmlElement(required = true)
    protected AdminLandingPageSuggestionStreamEntryRepresentationJAXB landingPageSuggestionDetails;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the entrytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntrytype() {
        return entrytype;
    }

    /**
     * Sets the value of the entrytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntrytype(String value) {
        this.entrytype = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public long getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(long value) {
        this.weight = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the dealDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminDealStreamEntryRepresentationJAXB }
     *     
     */
    public AdminDealStreamEntryRepresentationJAXB getDealDetails() {
        return dealDetails;
    }

    /**
     * Sets the value of the dealDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminDealStreamEntryRepresentationJAXB }
     *     
     */
    public void setDealDetails(AdminDealStreamEntryRepresentationJAXB value) {
        this.dealDetails = value;
    }

    /**
     * Gets the value of the permissionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminPermissionStreamEntryRepresentationJAXB }
     *     
     */
    public AdminPermissionStreamEntryRepresentationJAXB getPermissionDetails() {
        return permissionDetails;
    }

    /**
     * Sets the value of the permissionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminPermissionStreamEntryRepresentationJAXB }
     *     
     */
    public void setPermissionDetails(AdminPermissionStreamEntryRepresentationJAXB value) {
        this.permissionDetails = value;
    }

    /**
     * Gets the value of the userPermissionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminUserPermStreamEntryRepresentationJAXB }
     *     
     */
    public AdminUserPermStreamEntryRepresentationJAXB getUserPermissionDetails() {
        return userPermissionDetails;
    }

    /**
     * Sets the value of the userPermissionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminUserPermStreamEntryRepresentationJAXB }
     *     
     */
    public void setUserPermissionDetails(AdminUserPermStreamEntryRepresentationJAXB value) {
        this.userPermissionDetails = value;
    }

    /**
     * Gets the value of the producerProductDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminProducerProductEntryRepresentationJAXB }
     *     
     */
    public AdminProducerProductEntryRepresentationJAXB getProducerProductDetails() {
        return producerProductDetails;
    }

    /**
     * Sets the value of the producerProductDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminProducerProductEntryRepresentationJAXB }
     *     
     */
    public void setProducerProductDetails(AdminProducerProductEntryRepresentationJAXB value) {
        this.producerProductDetails = value;
    }

    /**
     * Gets the value of the sponsoredPointDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminSponsoredPointsStreamEntryRepresentationJAXB }
     *     
     */
    public AdminSponsoredPointsStreamEntryRepresentationJAXB getSponsoredPointDetails() {
        return sponsoredPointDetails;
    }

    /**
     * Sets the value of the sponsoredPointDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminSponsoredPointsStreamEntryRepresentationJAXB }
     *     
     */
    public void setSponsoredPointDetails(AdminSponsoredPointsStreamEntryRepresentationJAXB value) {
        this.sponsoredPointDetails = value;
    }

    /**
     * Gets the value of the sponsoredRewardDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminSponsoredRewardStreamEntryRepresentationJAXB }
     *     
     */
    public AdminSponsoredRewardStreamEntryRepresentationJAXB getSponsoredRewardDetails() {
        return sponsoredRewardDetails;
    }

    /**
     * Sets the value of the sponsoredRewardDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminSponsoredRewardStreamEntryRepresentationJAXB }
     *     
     */
    public void setSponsoredRewardDetails(AdminSponsoredRewardStreamEntryRepresentationJAXB value) {
        this.sponsoredRewardDetails = value;
    }

    /**
     * Gets the value of the sponsoredRequestDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminSponsoredRequestStreamEntryRepresentationJAXB }
     *     
     */
    public AdminSponsoredRequestStreamEntryRepresentationJAXB getSponsoredRequestDetails() {
        return sponsoredRequestDetails;
    }

    /**
     * Sets the value of the sponsoredRequestDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminSponsoredRequestStreamEntryRepresentationJAXB }
     *     
     */
    public void setSponsoredRequestDetails(AdminSponsoredRequestStreamEntryRepresentationJAXB value) {
        this.sponsoredRequestDetails = value;
    }

    /**
     * Gets the value of the producerReviewDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminProducerReviewStreamEntryRepresentationJAXB }
     *     
     */
    public AdminProducerReviewStreamEntryRepresentationJAXB getProducerReviewDetails() {
        return producerReviewDetails;
    }

    /**
     * Sets the value of the producerReviewDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminProducerReviewStreamEntryRepresentationJAXB }
     *     
     */
    public void setProducerReviewDetails(AdminProducerReviewStreamEntryRepresentationJAXB value) {
        this.producerReviewDetails = value;
    }

    /**
     * Gets the value of the productReviewDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminProductReviewStreamEntryRepresentationJAXB }
     *     
     */
    public AdminProductReviewStreamEntryRepresentationJAXB getProductReviewDetails() {
        return productReviewDetails;
    }

    /**
     * Sets the value of the productReviewDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminProductReviewStreamEntryRepresentationJAXB }
     *     
     */
    public void setProductReviewDetails(AdminProductReviewStreamEntryRepresentationJAXB value) {
        this.productReviewDetails = value;
    }

    /**
     * Gets the value of the dealReviewDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminDealReviewStreamEntryRepresentationJAXB }
     *     
     */
    public AdminDealReviewStreamEntryRepresentationJAXB getDealReviewDetails() {
        return dealReviewDetails;
    }

    /**
     * Sets the value of the dealReviewDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminDealReviewStreamEntryRepresentationJAXB }
     *     
     */
    public void setDealReviewDetails(AdminDealReviewStreamEntryRepresentationJAXB value) {
        this.dealReviewDetails = value;
    }

    /**
     * Gets the value of the badgeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminBadgeStreamEntryRepresentationJAXB }
     *     
     */
    public AdminBadgeStreamEntryRepresentationJAXB getBadgeDetails() {
        return badgeDetails;
    }

    /**
     * Sets the value of the badgeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminBadgeStreamEntryRepresentationJAXB }
     *     
     */
    public void setBadgeDetails(AdminBadgeStreamEntryRepresentationJAXB value) {
        this.badgeDetails = value;
    }

    /**
     * Gets the value of the landingPageSuggestionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AdminLandingPageSuggestionStreamEntryRepresentationJAXB }
     *     
     */
    public AdminLandingPageSuggestionStreamEntryRepresentationJAXB getLandingPageSuggestionDetails() {
        return landingPageSuggestionDetails;
    }

    /**
     * Sets the value of the landingPageSuggestionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminLandingPageSuggestionStreamEntryRepresentationJAXB }
     *     
     */
    public void setLandingPageSuggestionDetails(AdminLandingPageSuggestionStreamEntryRepresentationJAXB value) {
        this.landingPageSuggestionDetails = value;
    }

}
