//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.29 at 10:54:32 AM IST 
//


package com.ubiquity.common.jaxb.admin.stream;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ubiquity.common.jaxb.admin.stream package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GenericStreamEntryRepresentation_QNAME = new QName("", "GenericStreamEntryRepresentation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ubiquity.common.jaxb.admin.stream
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdminPermissionStreamEntryRepresentationJAXB }
     * 
     */
    public AdminPermissionStreamEntryRepresentationJAXB createAdminPermissionStreamEntryRepresentationJAXB() {
        return new AdminPermissionStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link AdminStreamEntryRepresentationJAXB }
     * 
     */
    public AdminStreamEntryRepresentationJAXB createAdminStreamEntryRepresentationJAXB() {
        return new AdminStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link StreamDealDetailJAXB }
     * 
     */
    public StreamDealDetailJAXB createStreamDealDetailJAXB() {
        return new StreamDealDetailJAXB();
    }

    /**
     * Create an instance of {@link StreamImageJAXB }
     * 
     */
    public StreamImageJAXB createStreamImageJAXB() {
        return new StreamImageJAXB();
    }

    /**
     * Create an instance of {@link ProducerAddressDetailJAXB }
     * 
     */
    public ProducerAddressDetailJAXB createProducerAddressDetailJAXB() {
        return new ProducerAddressDetailJAXB();
    }

    /**
     * Create an instance of {@link AdminProductReviewStreamEntryRepresentationJAXB }
     * 
     */
    public AdminProductReviewStreamEntryRepresentationJAXB createAdminProductReviewStreamEntryRepresentationJAXB() {
        return new AdminProductReviewStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link AdminSponsoredRequestStreamEntryRepresentationJAXB }
     * 
     */
    public AdminSponsoredRequestStreamEntryRepresentationJAXB createAdminSponsoredRequestStreamEntryRepresentationJAXB() {
        return new AdminSponsoredRequestStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link StreamProductDetailJAXB }
     * 
     */
    public StreamProductDetailJAXB createStreamProductDetailJAXB() {
        return new StreamProductDetailJAXB();
    }

    /**
     * Create an instance of {@link AdminDealReviewStreamEntryRepresentationJAXB }
     * 
     */
    public AdminDealReviewStreamEntryRepresentationJAXB createAdminDealReviewStreamEntryRepresentationJAXB() {
        return new AdminDealReviewStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link AdminProducerReviewStreamEntryRepresentationJAXB }
     * 
     */
    public AdminProducerReviewStreamEntryRepresentationJAXB createAdminProducerReviewStreamEntryRepresentationJAXB() {
        return new AdminProducerReviewStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link StreamProducerDetailJAXB }
     * 
     */
    public StreamProducerDetailJAXB createStreamProducerDetailJAXB() {
        return new StreamProducerDetailJAXB();
    }

    /**
     * Create an instance of {@link StreamTagsDetailJAXB }
     * 
     */
    public StreamTagsDetailJAXB createStreamTagsDetailJAXB() {
        return new StreamTagsDetailJAXB();
    }

    /**
     * Create an instance of {@link AdminDealStreamEntryRepresentationJAXB }
     * 
     */
    public AdminDealStreamEntryRepresentationJAXB createAdminDealStreamEntryRepresentationJAXB() {
        return new AdminDealStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link AdminProducerProductEntryRepresentationJAXB }
     * 
     */
    public AdminProducerProductEntryRepresentationJAXB createAdminProducerProductEntryRepresentationJAXB() {
        return new AdminProducerProductEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link AdminStreamRepresentationJAXB }
     * 
     */
    public AdminStreamRepresentationJAXB createAdminStreamRepresentationJAXB() {
        return new AdminStreamRepresentationJAXB();
    }

    /**
     * Create an instance of {@link AdminLandingPageSuggestionStreamEntryRepresentationJAXB }
     * 
     */
    public AdminLandingPageSuggestionStreamEntryRepresentationJAXB createAdminLandingPageSuggestionStreamEntryRepresentationJAXB() {
        return new AdminLandingPageSuggestionStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link AdminSponsoredPointsStreamEntryRepresentationJAXB }
     * 
     */
    public AdminSponsoredPointsStreamEntryRepresentationJAXB createAdminSponsoredPointsStreamEntryRepresentationJAXB() {
        return new AdminSponsoredPointsStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link AdminSponsoredRewardStreamEntryRepresentationJAXB }
     * 
     */
    public AdminSponsoredRewardStreamEntryRepresentationJAXB createAdminSponsoredRewardStreamEntryRepresentationJAXB() {
        return new AdminSponsoredRewardStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link AdminBadgeStreamEntryRepresentationJAXB }
     * 
     */
    public AdminBadgeStreamEntryRepresentationJAXB createAdminBadgeStreamEntryRepresentationJAXB() {
        return new AdminBadgeStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link StreamUserDetailJAXB }
     * 
     */
    public StreamUserDetailJAXB createStreamUserDetailJAXB() {
        return new StreamUserDetailJAXB();
    }

    /**
     * Create an instance of {@link AdminUserPermStreamEntryRepresentationJAXB }
     * 
     */
    public AdminUserPermStreamEntryRepresentationJAXB createAdminUserPermStreamEntryRepresentationJAXB() {
        return new AdminUserPermStreamEntryRepresentationJAXB();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdminStreamEntryRepresentationJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenericStreamEntryRepresentation")
    public JAXBElement<AdminStreamEntryRepresentationJAXB> createGenericStreamEntryRepresentation(AdminStreamEntryRepresentationJAXB value) {
        return new JAXBElement<AdminStreamEntryRepresentationJAXB>(_GenericStreamEntryRepresentation_QNAME, AdminStreamEntryRepresentationJAXB.class, null, value);
    }

}
