//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 08:58:08 PM IST 
//


package com.ubiquity.common.jaxb.webexception;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ubiquity.common.jaxb.webexception package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WebServiceExceptionForm_QNAME = new QName("", "webServiceExceptionForm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ubiquity.common.jaxb.webexception
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WebServiceExceptionJAXB }
     * 
     */
    public WebServiceExceptionJAXB createWebServiceExceptionJAXB() {
        return new WebServiceExceptionJAXB();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebServiceExceptionJAXB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "webServiceExceptionForm")
    public JAXBElement<WebServiceExceptionJAXB> createWebServiceExceptionForm(WebServiceExceptionJAXB value) {
        return new JAXBElement<WebServiceExceptionJAXB>(_WebServiceExceptionForm_QNAME, WebServiceExceptionJAXB.class, null, value);
    }

}
